(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var D4=function(a){a.ma("cardstatechange",a.Ai()&&a.wm()?1:0)},E4=function(a,b){var c=g.Ma(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},c1a=function(a){var b=g.Fl(a);
a=g.Il(a);return new g.ul(b.x,b.y,a.width,a.height)},d1a=function(a){return Math.pow(a,3)},e1a=function(a){return 3*a*a-2*a*a*a},H4=function(a){a=g.Pa(a);
delete F4[a];g.Bf(F4)&&G4&&G4.stop()},g1a=function(){G4||(G4=new g.Yn(function(){f1a()},20));
var a=G4;a.isActive()||a.start()},f1a=function(){var a=g.Ua();
g.of(F4,function(b){h1a(b,a)});
g.Bf(F4)||g1a()},I4=function(a,b,c,d){g.so.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.S=b;this.duration=c;this.I=d;this.coords=[];this.progress=this.J=0;this.D=null},h1a=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.J=1E3/(b-a.D);a.D=b;i1a(a,a.progress);1==a.progress?(a.j=0,H4(a),a.onFinish(),a.Uz()):a.Sc()&&a.qF()},i1a=function(a,b){"function"===typeof a.I&&(b=a.I(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.S[c]-a.u[c])*b+a.u[c]},j1a=function(a,b){g.df.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.J;this.state=b.j},J4=function(a,b,c,d,e){I4.call(this,b,c,d,e);
this.element=a},k1a=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
J4.call(this,a,b,c,d,e)},K4=function(a){g.K.call(this);
this.u=a||window;this.j=[]},L4=function(a){return a.baseUrl||null},M4=function(a,b){return g.sm(g.Ok(a,b),function(c){return!!c})},l1a=function(a,b,c){function d(X){var R=X.hovercardButton;
if(!R)return null;R=R.subscribeButtonRenderer;if(!R)return null;var oa=f(R.unsubscribedButtonText),sa=f(R.subscribedButtonText);if(R.subscribed){var Aa=f(R.subscriberCountWithUnsubscribeText);var xa=f(R.subscriberCountText)}else Aa=f(R.subscriberCountText),xa=f(R.subscriberCountWithSubscribeText);var ta=null;if(X.signinEndpoint){ta=E4(X,"signinEndpoint","webNavigationEndpointData","url");if(!ta){var Ia,Ja,qa;ta=null==(Ia=R.signInEndpoint)?void 0:null==(Ja=Ia.commandMetadata)?void 0:null==(qa=Ja.webCommandMetadata)?
void 0:qa.url}if(!ta)return null}return oa&&(sa||ta)?{subscribed:R.subscribed,subscribeText:oa,subscribeCount:Aa,unsubscribeText:sa,unsubscribeCount:xa,enabled:R.enabled,signinUrl:ta,classic:X.useClassicSubscribeButton}:null}
function e(X){if(X){var R=[],oa=X.videoId;oa&&R.push("v="+oa);(oa=X.playlistId)&&R.push("list="+oa);(X=X.startTimeSeconds)&&R.push("t="+X);return"/watch?"+R.join("&")}}
function f(X){if(!X)return null;var R=X.simpleText;return R?R:X.runs?g.Ok(X.runs,function(oa){return oa.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,u=null,w=null,y=null,A=!1,B=null,D=null,G=null,F=null,I=null,O=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:(O=l.watchEndpoint,m=e(O)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,u=f(p.text),p="LIVE"===p.style):u=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:(O=l.watchEndpoint,m=e(O)),n=!1,q=a,w=f(b.playlistLength);
else if("CHANNEL"===h){if(A=E4(l,"browseEndpoint","browseId"))y=A,m="/channel/"+y;n=!1;q="new";(A=!!b.isSubscribe)?B=d(b):D=f(b.subscribersText)}else"WEBSITE"===h?((G=E4(l,"urlEndpoint","url"))&&(m=G),n=!0,q="new",G=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(F=f(b.productPrice)),b.additionalFeesText&&(I=f(b.additionalFeesText)),(n=E4(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=E4(b,"title","accessibility","accessibilityData","label");var L=b.endpoint?b.endpoint.clickTrackingParams:
null,P="";if(b.metadata){var Q=f(b.metadata);Q&&(P=Q)}return{id:"element-"+c,type:h,title:f(b.title),metadata:P,callToAction:f(b.callToAction),CO:b.image,iconUrl:G,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:u,isLiveVideo:p,playlistLength:w,channelId:y,subscribeButton:B,subscribersText:D,isSubscribe:A,targetUrl:m||null,e_:n,sessionData:L?{itct:L}:null,y5:q,Sx:a?a:
null,isPlaceholder:b.isPlaceholder,impressionUrls:M4(b.impressionUrls||[],L4),PZ:M4(b.hovercardShowUrls||[],L4),clickUrls:M4(l.loggingUrls||[],L4),visualElement:g.uz(b.trackingParams),productPrice:F,additionalFeesText:I,watchEndpoint:O||null}},m1a=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:M4(a.impressionUrls||[],L4),elements:M4(a.elements||[],function(d,e){return l1a(b,d,e)})};
a.trackingParams&&(c.visualElement=g.uz(a.trackingParams));return c},n1a=function(a){g.dO.call(this,a);
this.B=this.endscreen=null;this.j={};this.D={};this.C=this.u=null;this.J=[];this.Z=!0;this.I=0;a=a.V();this.S=g.TF(a)||g.XF(a);this.ea=a.experiments.jb("web_rounded_thumbnails");this.events=new g.ZD(this);g.M(this,this.events);this.events.T(this.player,g.uA("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.vA("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.Bb);this.events.T(window,"focus",this.C3);this.load();var b=g.ih("STYLE");(g.ah("HEAD")[0]||
document.body).appendChild(b);g.cf(this,function(){g.ph(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},o1a=function(a){return a.player.getVideoData().C?"current":a.S?"new":"current"},N4=function(a){return"creator-endscreen-editor"===a.player.V().playerStyle},p1a=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=m1a(f,o1a(a))));O4(a,f)},
urlParams:{v:c},withCredentials:!0};a.S&&(c.urlParams.ptype="embedded");var d=b.Wq;d&&(c.postParams={ad_tracking:d});if(b=g.PBa(b))if(b=g.lg(b),b=g.kg(b))a.B=g.Cu(b,c)},O4=function(a,b,c){c=void 0===c?!0:c;
a.player.Ff("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.r(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.D={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&q1a(a);c=[];d=new g.sA(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.V().isMobile||(a.u=new g.W({F:"div",N:"ytp-ce-shadow"}),g.CN(a.player,a.u.element,4),a.C=new g.KL(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=r1a(a,e);if(f){a.j[e.id]=f;a.D[e.id]=e;g.CN(a.player,f.element,4);var h=new g.sA(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);s1a(a,
f,e)}else g.rz(new g.Rv("buildEndscreenElement null",e))}a.player.qe(c);a.Bb()}},q1a=function(a){var b=g.Az(),c=g.Bz();
c&&b&&a.endscreen.visualElement&&g.Fz(void 0,c,b,[a.endscreen.visualElement])},r1a=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={F:"div",Ga:["ytp-ce-element","ytp-ce-video"],X:{tabindex:"0","aria-label":b.Sx||"","aria-hidden":"true"},W:[{F:"div",N:"ytp-ce-element-shadow"},{F:"div",N:"ytp-ce-covering-image",X:P4(b)},{F:"div",N:"ytp-ce-covering-shadow-top"},{F:"a",N:"ytp-ce-covering-overlay",X:{href:Q4(a,b.targetUrl),tabindex:"-1"},W:[{F:"div",Ga:["ytp-ce-video-title","ytp-webkit-ellipsis"],X:{dir:g.wo(b.title||"")},qa:b.title},{F:"div",N:b.isLiveVideo?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
qa:b.videoDuration||void 0}]}]};c=new g.W(a);break;case "PLAYLIST":a={F:"div",Ga:["ytp-ce-element","ytp-ce-playlist"],X:{tabindex:"0","aria-label":b.Sx||"","aria-hidden":"true"},W:[{F:"div",N:"ytp-ce-element-shadow"},{F:"div",N:"ytp-ce-covering-image",X:P4(b)},{F:"div",N:"ytp-ce-covering-shadow-top"},{F:"a",N:"ytp-ce-covering-overlay",X:{href:Q4(a,b.targetUrl),tabindex:"-1"},W:[{F:"div",Ga:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],X:{dir:g.wo(b.title||"")},qa:b.title},{F:"div",N:"ytp-ce-playlist-count",
W:[{F:"div",N:"ytp-ce-playlist-icon"},{F:"div",N:"ytp-ce-playlist-count-text",qa:b.playlistLength||void 0}]}]}]};c=new g.W(a);break;case "CHANNEL":c={F:"div",Ga:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],X:{tabindex:"0","aria-label":b.Sx||"","aria-hidden":"true"},W:[{F:"div",N:"ytp-ce-element-shadow"},{F:"div",N:"ytp-ce-expanding-overlay",W:[{F:"div",N:"ytp-ce-expanding-overlay-hider"},{F:"div",N:"ytp-ce-expanding-overlay-background"},{F:"div",N:"ytp-ce-expanding-overlay-content",
W:[{F:"div",N:"ytp-ce-expanding-overlay-body",W:[{F:"div",N:"ytp-ce-expanding-overlay-body-padding",W:[{F:"a",Ga:["ytp-ce-channel-title","ytp-ce-link"],X:{href:Q4(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.wo(b.title||"")},qa:b.title},b.subscribeButton?{F:"div",N:"ytp-ce-subscribe-container",W:[{F:"div",N:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{F:"div",N:"ytp-ce-channel-subscribers-text",qa:b.subscribersText}:"",b.metadata?{F:"div",Ga:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],qa:b.metadata}:""]}]}]}]},{F:"div",N:"ytp-ce-expanding-image",X:P4(b)}]};c=new g.W(c);var d=g.bh(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.go(d,"ytp-ce-subscribe-button");if(a.player.V().isMobile){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.hP(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,
!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={F:"div",Ga:["ytp-ce-element","ytp-ce-website"],X:{tabindex:"0","aria-label":b.Sx||"","aria-hidden":"true"},W:[{F:"div",N:"ytp-ce-element-shadow"},{F:"div",N:"ytp-ce-expanding-overlay",W:[{F:"div",N:"ytp-ce-expanding-overlay-hider"},{F:"div",N:"ytp-ce-expanding-overlay-background"},{F:"div",N:"ytp-ce-expanding-overlay-content",
W:[{F:"div",N:"ytp-ce-expanding-overlay-body",W:[{F:"div",N:"ytp-ce-expanding-overlay-body-padding",W:[{F:"div",N:"ytp-ce-website-title",X:{dir:g.wo(b.title||"")},qa:b.title},{F:"div",N:"ytp-ce-website-metadata",qa:b.metadata},{F:"a",Ga:["ytp-ce-website-goto","ytp-ce-link"],X:{href:Q4(a,b.targetUrl),target:"_blank",tabindex:"-1"},qa:b.callToAction}]}]}]}]},{F:"div",N:"ytp-ce-expanding-image",X:P4(b)},{F:"div",N:"ytp-ce-expanding-icon",X:t1a(b.iconUrl)}]};c=new g.W(a);break;case "CREATOR_MERCHANDISE":c=
"",b.productPrice&&(c={F:"div",N:"ytp-ce-merchandise-price-container",W:[{F:"div",N:"ytp-ce-merchandise-price",qa:b.productPrice}]},b.additionalFeesText&&c.W.push({F:"div",N:"ytp-ce-merchandise-additional-fees",qa:b.additionalFeesText})),a={F:"div",Ga:["ytp-ce-element","ytp-ce-merchandise"],X:{tabindex:"0","aria-label":b.Sx||"","aria-hidden":"true"},W:[{F:"div",N:"ytp-ce-element-shadow"},{F:"div",N:"ytp-ce-expanding-overlay",W:[{F:"div",N:"ytp-ce-expanding-overlay-hider"},{F:"div",N:"ytp-ce-expanding-overlay-background"},
{F:"div",N:"ytp-ce-expanding-overlay-content",W:[{F:"div",N:"ytp-ce-expanding-overlay-body",W:[{F:"div",N:"ytp-ce-expanding-overlay-body-padding",W:[{F:"div",N:"ytp-ce-merchandise-title",X:{dir:g.wo(b.title||"")},qa:b.title},c,{F:"div",N:"ytp-ce-merchandise-metadata",qa:b.metadata},{F:"a",Ga:["ytp-ce-merchandise-goto","ytp-ce-link"],X:{href:Q4(a,b.targetUrl),target:"_blank",tabindex:"-1"},qa:b.callToAction}]}]}]}]},{F:"div",N:"ytp-ce-expanding-image",X:P4(b)},{F:"div",N:"ytp-ce-merchandise-invideo-cta-container",
W:[{F:"div",N:"ytp-ce-merchandise-invideo-cta",qa:b.callToAction||void 0}]}]},c=new g.W(a)}b.isPlaceholder&&g.go(c.element,"ytp-ce-placeholder");return c},P4=function(a){if(a.CO)var b=a.CO.thumbnails;
return t1a(b?b[b.length-1].url:null)},t1a=function(a){return a?{style:"background-image: url("+a+")"}:{}},s1a=function(a,b,c){function d(m){m&&(b.Ra("blur",function(){"none"!=m.style.display&&a.Z&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.go(b.element,"ytp-ce-force-expand"),R4(a,c.id,!0)):(g.io(b.element,"ytp-ce-force-expand"),g.io(b.element,"ytp-ce-element-hover"),R4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Ra("mouseenter",function(){u1a(a,b,c)});
b.Ra("mouseleave",function(){v1a(a,b,c)});
a.player.V().isMobile||b.Ra("click",function(){g.go(b.element,"ytp-ce-element-hover")});
b.Ra("click",function(m){w1a(a,c,m)});
b.Ra("keypress",function(m){w1a(a,c,m)});
b.Ra("focus",function(){u1a(a,b,c)});
b.Ra("blur",function(){v1a(a,b,c)});
b.Ra("touchstart",function(){u1a(a,b,c)});
var l=g.dh("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.io(b.element,"ytp-ce-element-hover");g.io(b.element,"ytp-ce-force-expand")});
b.Ra("keydown",function(m){a.Z=9===m.keyCode&&!m.shiftKey});
d(g.dh("ytp-sb-subscribe",b.element));d(g.dh("ytp-sb-unsubscribe",b.element));b.Ra("focus",f);b.Ra("blur",h)},w1a=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.fo(d,"ytp-ce-element");){g.fo(d,"subscribe-label")&&x1a(a,b);
if(g.fo(d,"ytp-ce-channel-subscribe"))return;d=g.qh(d)}if(!d||g.fo(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])v1a(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.y5)x1a(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.lg(Q4(a,b.targetUrl)),g.kM(g.kg(c),void 0,b.sessionData);else{var e=g.mG(a.player.V())||a.player.getVideoData().C,f=function(){var h=Q4(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.nu(h);e&&n&&(n.v||
n.list)?a.player.Ll(n.v,l,n.list,!1,void 0,m||void 0):g.jM(h,l)};
x1a(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},Q4=function(a,b){a=a.player.V();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.wG(a)+b}else return"";return b},u1a=function(a,b,c){g.fo(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.go(b.element,"ytp-ce-element-hover"):a.player.V().isMobile?(new g.Yn(function(){g.go(b.element,"ytp-ce-element-hover")},200)).start():g.go(b.element,"ytp-ce-element-hover"),S4(a,c.PZ),R4(a,c.id,!0))},v1a=function(a,b,c){g.io(b.element,"ytp-ce-element-hover");
g.io(b.element,"ytp-ce-force-expand");R4(a,c.id,!1)},R4=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.r(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.ko(a.j[e].element,"ytp-ce-element-shadow-show",c)},S4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||N4(a))c&&c();else{b=y1a(a,b);var e=0,f=!1,h=new g.Yn(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.Ww(b[a],d)}},x1a=function(a,b,c){S4(a,b.clickUrls,c);
(a=g.Bz())&&b.e_&&g.Lz(a,b.visualElement)},y1a=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(z1a(b[d],c));return a},z1a=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},A1a=function(a){return"string"===typeof a?a:""},T4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},B1a=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},U4=function(a){return a.value?a.value:null},V4=function(a){if(!a)return null;
var b=g.lg(A1a(a.value));b=g.kg(b);if(!b)return null;var c=T4(a.target,C1a,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new B1a(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},D1a=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},G1a=function(a){if(!a)return null;
var b=T4(a.type,E1a),c=T4(a.trigger,F1a);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=V4(a?a:null);return b?new D1a(b,c,a):null},H1a=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},I1a=function(a,b){return g.Ub(a.action,b)},J1a=function(a,b){this.context=a;
this.j=b},K1a=function(a){return a.customMessage?W4("div","iv-card-message",a.customMessage):""},X4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{F:"div",N:"iv-card-image",X:{style:a},W:c}},L1a=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.r(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(W4("li","",c.value));return{F:"ul",N:"iv-card-meta-info",W:b}},W4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.wo(c);return{F:a,X:b,qa:c}},M1a=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.gy&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.gy+");");c.dir=g.wo(a.customMessage);var d=[{F:"span",qa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({F:"span",N:"iv-card-link-icon"}));return{F:"div",Ga:b,X:c,W:d}},Y4=function(a,b,c,d){if(d){b=g.r(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.tracking.click,5)}},N1a=function(a,b){this.merchant=a;
this.price=b},O1a=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},P1a=function(a,b){return b?b:O1a(a)?"current":"new"},Z4=function(a,b){g.K.call(this);
var c=this;this.element=a;this.context=b;this.yb=!1;this.Ya=new Map;this.fb=new Map;this.context.G.addEventListener(g.uA("annotations_module"),function(d){(d=c.Ya.get(d))&&d.apply(c)});
this.context.G.addEventListener(g.vA("annotations_module"),function(d){(d=c.fb.get(d))&&d.apply(c)})},$4=function(a,b,c,d,e,f,h){a.context.j.Ra(b,"click",function(l){a.rF(c,d,e,f||[],h||0,l)});
a.context.j.Ra(b,"touchstart",function(){a.yb=!1});
a.context.j.Ra(b,"touchmove",function(){a.yb=!0})},Q1a=function(a){var b;
return(null==(b=g.av(a,g.SH))?0:b.url)?g.av(a,g.SH).url:(a=g.av(a,g.WG))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},a5=function(a,b,c){return{impression:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
NS:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
EE:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},R1a=function(a,b,c){Z4.call(this,b,c);
var d=this;this.G=a;this.eventId=null;this.Qa=this.Rb=this.B=this.isInitialized=!1;this.xa=null;this.cards=[];this.Gb=this.S=this.La=this.D=this.Va=this.j=null;this.ea=[];this.oa=this.J=this.sf=this.Ia=null;this.I=0;this.Ba=new g.Yn(function(){},c.Y.kf?4E3:3E3);
g.M(this,this.Ba);this.ob=new g.Yn(function(){});
g.M(this,this.ob);this.Aa=new J1a(c,function(e,f,h,l,m,n){$4(d,e,f,h,l,m,n)});
this.Z=new g.W({F:"div",N:"iv-drawer",X:{id:"iv-drawer"},W:[{F:"div",N:"iv-drawer-header",X:{"aria-role":"heading"},W:[{F:"span",N:"iv-drawer-header-text"},{F:"button",Ga:["iv-drawer-close-button","ytp-button"],X:{"aria-label":"Ocultar tarjetas",tabindex:"0"}}]},{F:"div",N:"iv-drawer-content"}]});g.M(this,this.Z);this.C=this.Z.element;this.kb=new g.KL(this.Z,330);g.M(this,this.kb);this.Kb=g.dh("iv-drawer-header-text",this.C);this.u=g.dh("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Rb&&b5(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Rb=d.B)&&c5(d)});
this.G.addEventListener("videodatachange",this.Yp.bind(this))},S1a=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){b5(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){c5(a)});
var c=b.headerText;g.sh(a.Kb,c);a.S&&a.S.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ia=g.uz(b.trackingParams);a.J=g.uz(b.closeTrackingParams);a.sf=g.uz(b.iconTrackingParams)},T1a=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I,d=a.G.V().experiments.jb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.zA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,tracking:{},xm:null,Ej:e.trackingParams?g.uz(e.trackingParams):null,sf:f&&f.trackingParams?g.uz(f.trackingParams):null,imageUrl:"",displayDomain:null,
showLinkIcon:!1,gy:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};d5(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.zA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:e5(a,c,b,f),sponsored:!1,tracking:a5(f,e,f.command),xm:f.trackingParams?g.uz(f.trackingParams):null,Ej:e.trackingParams?g.uz(e.trackingParams):null,sf:l&&l.trackingParams?g.uz(l.trackingParams):null,imageUrl:f5(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.zA(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,gy:null,title:f.title?g.zA(f.title):"",customMessage:f.callToAction?g.zA(f.callToAction):"",url:g.av(f.command,g.SH).url?V4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.av(f.command,g.SH).url}):null,onClickCommand:null};d5(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"collaborator",teaserText:g.zA(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:e5(a,c,b,e),sponsored:!1,tracking:a5(e,f,e.endpoint),xm:e.trackingParams?g.uz(e.trackingParams):null,Ej:f.trackingParams?g.uz(f.trackingParams):null,sf:l&&l.trackingParams?g.uz(l.trackingParams):null,channelId:g.av(e.endpoint,g5).browseId,customMessage:e.customText?g.zA(e.customText):null,profileImageUrl:f5(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.zA(e.channelName):"",metaInfo:[e.subscriberCountText?g.zA(e.subscriberCountText):""],url:V4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.av(e.endpoint,g5).canonicalBaseUrl?g.av(e.endpoint,g5).canonicalBaseUrl:"/channel/"+g.av(e.endpoint,g5).browseId}),onClickCommand:null};d5(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"playlist",teaserText:g.zA(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:e5(a,c,b,e),sponsored:!1,tracking:a5(e,f,e.action),xm:e.trackingParams?g.uz(e.trackingParams):null,Ej:f.trackingParams?g.uz(f.trackingParams):null,sf:l&&l.trackingParams?g.uz(l.trackingParams):null,KA:f5(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.zA(e.customMessage):null,playlistVideoCount:g.zA(e.playlistVideoCount),title:e.playlistTitle?g.zA(e.playlistTitle):"",metaInfo:[e.channelName?
g.zA(e.channelName):"",e.videoCountText?g.zA(e.videoCountText):""],url:V4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Q1a(e.action)}),onClickCommand:null};d5(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"video",teaserText:g.zA(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:e5(a,c,b,e),sponsored:!1,tracking:a5(e,f,e.action),xm:e.trackingParams?g.uz(e.trackingParams):null,Ej:f.trackingParams?g.uz(f.trackingParams):null,sf:l&&l.trackingParams?g.uz(l.trackingParams):null,KA:f5(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.zA(e.lengthString):null,customMessage:e.customMessage?g.zA(e.customMessage):null,title:e.videoTitle?g.zA(e.videoTitle):"",metaInfo:[e.channelName?
g.zA(e.channelName):"",e.viewCountText?g.zA(e.viewCountText):""],isLiveNow:!!e.badge,url:V4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Q1a(e.action)}),onClickCommand:null};d5(a,b)}}}}}a.I++},f5=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},e5=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},V1a=function(a,b){if(b=U1a(a,b))b===a.j&&(a.j=null),a.G.removeCueRange(b.card.id),g.ph(b.OG),g.ac(a.cards,b),a.KB(),h5(a)},b5=function(a,b,c){if(!a.B){a.kb.show();
a.Va=new g.Yn(function(){g.go(a.context.G.getRootNode(),g.qT.IV_DRAWER_OPEN)},0);
a.Va.start();a.xa=g.Ax(a.u,"mousewheel",function(h){a.Ba.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.Bz();d&&a.Ia&&a.J&&g.Jz(d,[a.Ia,a.J]);b={TRIGGER_TYPE:b};for(var e=g.r(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.lQ||(f.lQ=!0,W1a(a.context.logger,f.card.tracking.impression,b)),d&&g.Jz(d,[f.card.xm]);D4(a.G);c&&(a.D=new g.Yn(function(){a.La=a.S;a.Gb.focus()},330),a.D.start())}},c5=function(a){a.B&&(a.kb.hide(),g.Bx(a.xa),a.xa=null,g.io(a.context.G.getRootNode(),g.qT.IV_DRAWER_OPEN),a.B=!1,D4(a.G),a.D&&a.D.stop(),a.D=new g.Yn(function(){a.La&&(a.La.focus(),a.La=null)},330),
a.D.start())},Y1a=function(a){g.ho(a.element,[g.qT.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.CN(a.G,a.C,5);X1a(a);a.S=g.dh("ytp-cards-button",a.G.getRootNode());a.Gb=g.dh("iv-drawer-close-button",a.C);a.isInitialized=!0},X1a=function(a){var b=g.dh("iv-drawer-close-button",a.C);
a.context.j.Ra(b,"click",a.eY,a);a.context.j.Ra(a.u,"touchend",function(){a.Ba.start()});
a.context.j.Ra(a.u,"scroll",a.xY,a);a.context.u.subscribe("onHideControls",function(){a.Qa=!0});
a.context.u.subscribe("onShowControls",function(){a.Qa=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Qa=g.fo(a.G.getRootNode(),"ytp-autohide")});
a.ea.push(g.Ux("iv-button-shown",a.q_,a));a.ea.push(g.Ux("iv-button-hidden",a.p_,a));a.ea.push(g.Ux("iv-teaser-shown",a.sU,a));a.ea.push(g.Ux("iv-teaser-hidden",a.s_,a));a.ea.push(g.Ux("iv-teaser-clicked",a.rU,a))},Z1a=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.av(b.onClickCommand,g.cZa))?void 0:c.targetId)?(a.oa=b,!0):!1},$1a=function(a,b){var c,d=null==(c=a.G.getVideoData())?void 0:c.multiMarkersPlayerBarRenderer;
if(null==d?0:d.markersMap){var e;for(c=0;(null==(e=d)?void 0:e.markersMap.length)>c;c++){var f=void 0,h=null==(f=d)?void 0:f.markersMap[c];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.av(h[0],g.A_a))?void 0:d.timeRangeStartMillis)||0,a.oa=null,!0}}a.oa=b;return!1},d5=function(a,b){if(!Z1a(a,b)||$1a(a,b)){var c=a2a(a,b);
if(c){var d={card:b,OG:c.element,lQ:!1};if(!b.onClickCommand){a.isInitialized||Y1a(a);V1a(a,b.id);var e=b2a(a,d);g.ic(a.cards,e,0,d);c.Ca(a.u,e);a.KB()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.j=d,h5(a),c2a(a,d),b5(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.G.getCurrentTime(),5E3>c&&c>b.startMs&&d2a(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){d2a(a,d)}),h5(a))}}},a2a=function(a,b){switch(b.type){case "simple":var c=a.Aa;
var d=b.displayDomain?{F:"div",N:"iv-card-image-text",qa:b.displayDomain}:void 0;var e=M1a(b);d={F:"div",Ga:["iv-card"],W:[{F:"a",N:"iv-click-target",X:{href:b.url?U4(b.url)||"":""},W:[X4(b.imageUrl,d),{F:"div",N:"iv-card-content",W:[W4("h2",void 0,b.title),e]}]}]};d=new g.W(d);Y4(c,g.ch("iv-click-target",d.element),b,b.url);b=d;break;case "collaborator":c=a.Aa;d={F:"div",Ga:["iv-card","iv-card-channel"],W:[{F:"a",Ga:["iv-click-target"],X:{href:U4(b.url)||"","data-ytid":b.channelId},W:[X4(b.profileImageUrl),
{F:"div",N:"iv-card-content",W:[K1a(b),{F:"h2",N:"iv-card-primary-link",qa:b.title},L1a(b)]}]}]};d=new g.W(d);Y4(c,g.ch("iv-click-target",d.element),b,b.url);b=d;break;case "playlist":c=a.Aa;d={F:"div",Ga:["iv-card","iv-card-playlist"],W:[{F:"a",N:"iv-click-target",X:{href:U4(b.url)||""},W:[X4(b.KA,{F:"div",N:"iv-card-image-overlay",W:[{F:"span",N:"iv-card-playlist-video-count",qa:b.playlistVideoCount}]}),{F:"div",N:"iv-card-content",W:[K1a(b),W4("h2","iv-card-primary-link",b.title),L1a(b)]}]}]};
d=new g.W(d);Y4(c,g.ch("iv-click-target",d.element),b,b.url);b=d;break;case "productListing":c=a.Aa;var f=!g.Xb(b.offers);d=["iv-card"];e="";var h=M1a(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",h=b.offers[0],f=[],h.price&&f.push({F:"div",N:"iv-card-offer-price",qa:h.price}),h.merchant&&f.push({F:"div",N:"iv-card-offer-merchant",qa:h.merchant}),h={F:"div",W:f});f=b.url?U4(b.url)||"":"";d={F:"div",Ga:d,X:{tabindex:"0"},W:[{F:"a",Ga:["iv-card-image","iv-click-target"],X:{style:"background-image: url("+
b.imageUrl+");",href:f,"aria-hidden":"true",tabindex:"-1"}},{F:"div",N:"iv-card-content",W:[b.sponsored?{F:"div",N:"iv-card-sponsored",W:["Patrocinado",{F:"div",N:"iv-ad-info-container",W:[{F:"div",N:"iv-ad-info",qa:"{{adInfo}}"},{F:"div",N:"iv-ad-info-icon-container",W:[{F:"div",N:"iv-ad-info-icon"},{F:"div",N:"iv-ad-info-callout"}]}]}]}:"",{F:"a",N:"iv-click-target",X:{href:f},W:[W4("h2",e,b.title),h]}]}]};d=new g.W(d);e=g.ih("span");g.sh(e,"Est\u00e1s viendo este producto porque creemos que es relevante para el v\u00eddeo. Es posible que Google reciba una compensaci\u00f3n de parte del comerciante.");
d.Vd(e,"adInfo");Y4(c,g.ch("iv-click-target",d.element),b,b.url);b=d;break;case "video":c=a.Aa;d=b.videoDuration?{F:"span",N:"iv-card-video-duration",qa:b.videoDuration}:void 0;e=b.isLiveNow?{F:"span",Ga:["yt-badge","yt-badge-live"],qa:"EN DIRECTO AHORA"}:null;f={F:"div",Ga:["iv-card","iv-card-video"],W:[{F:"a",N:"iv-click-target",X:{href:(null==(h=b.url)?void 0:U4(h))||""},W:[X4(b.KA,d),{F:"div",N:"iv-card-content",W:[K1a(b),W4("h2","iv-card-primary-link",b.title),L1a(b),e]}]}]};d=new g.W(f);Y4(c,
g.ch("iv-click-target",d.element),b,b.url);b=d;break;default:return null}a.G.V().experiments.jb("web_rounded_containers")&&g.go(b.element,"ytp-rounded-info");return b},b2a=function(a,b){if(0===a.cards.length)return 0;
a=g.Vb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},e2a=function(a){return a.j?"productListing"===a.j.card.type:g.Sd(a.cards,function(b){return"productListing"===b.card.type})},h5=function(a){g.ko(a.G.getRootNode(),"ytp-cards-shopping-active",e2a(a))},d2a=function(a,b){if(!g.fo(a.G.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.Bz(),d=a.j?a.j.card.sf:a.sf;
c&&d&&g.Kz(c,[d]);a.j=b;h5(a)}(c=a.isInitialized&&"none"==a.element.style.display)||(c=a.context.G.getPlayerState(),d=0===c&&0===a.context.G.getCurrentTime(),c=!(1===c||3===c||d));c||b.card.teaserDurationMs&&a.G.Pw(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs,onClickCommand:b.card.onClickCommand});a.ob.isActive()||((!a.B||!a.Ba.isActive()&&a.Qa)&&c2a(a,b),a.ob.start(910+b.card.teaserDurationMs))}},c2a=function(a,b){a.Z.rb?(b=new I4([0,
a.u.scrollTop],[0,b.OG.offsetTop],600,e1a),a.context.B.Ra(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Ra(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.ZK(a.Z,!0),a.u.scrollTop=b.OG.offsetTop,g.ZK(a.Z,!1))},i5=function(a){return a.j&&a.j.card?a.j.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},U1a=function(a,b){return g.Ub(a.cards,function(c){return c.card.id===b})},j5=function(a,b,c){Z4.call(this,a,b);
this.annotation=c;this.isActive=!1},f2a=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},k5=function(a,b,c){j5.call(this,a,b,c);
this.u=null;this.J=!1;this.B=null;this.C=!1;this.j=this.I=this.D=null},g2a=function(a,b){var c=void 0===c?0:c;
var d=c1a(b).width;g.Dl(b,d);c=new k1a(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,d1a);g.M(a,c);a.context.B.Ra(c,"begin",function(){g.Jl(b,!0)});
c.play()},j2a=function(a,b){if(b.channel_name){var c=a.createElement({F:"div",
Ga:["iv-branding-context-name"],qa:b.channel_name}),d=a.createElement({F:"div",Ga:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.hP(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.G),a.j.Ca(d));var f=a.createElement({F:"div",Ga:["iv-branding-context-subscribe-caret"]}),h=a.createElement({F:"div",Ga:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Jl(h,!1);a.context.Y.K("web_rounded_containers")&&g.go(h,"ytp-rounded-branding-context");var l=a.createElement({F:"div",Ga:["branding-context-container-outer"]});l.appendChild(h);g.xl(l,"right",b.image_width+"px");a.element.appendChild(l);a.B=new g.Yn(function(){h2a(a,h,l)},500);
g.M(a,a.B);a.context.j.Ra(a.element,"mouseover",function(){i2a(a,h,l,f,b.image_height)});
a.context.j.Ra(a.element,"mouseout",function(){a.B.start()})}},i2a=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.Il(b);a.j||(b.style.width=g.Cl(f.width,!0),c.style.width=g.Cl(f.width,!0));g.xl(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.xl(d,"right","1px");a.C=!0;g.Jl(b,!0);a.D=new g.Yn(function(){g.go(this.element,"iv-branding-active")},0,a);
a.D.start()}},h2a=function(a,b,c){g.io(a.element,"iv-branding-active");
a.I=new g.Yn(function(){g.Jl(b,!1);a.j||(c.style.width=g.Cl(0,!0))},250);
a.I.start();a.C=!1},k2a=function(a,b,c,d,e,f,h){this.j=a;
this.B=b;this.Y=c;this.videoData=d;this.logger=e;this.G=f;this.u=h},l2a=function(a,b,c){j5.call(this,a,b,c);
var d=this;this.S=this.isCollapsed=this.Z=!1;this.I=5E3;this.u=this.B=this.j=this.C=null;this.J=this.createElement({F:"div",Ga:["iv-promo-contents"]});this.D=new g.Yn(function(){d.j.setAttribute("aria-hidden","true");g.Jl(d.B,!1);g.Jl(d.u,!0)},700,this);
g.M(this,this.D)},n2a=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promoci\u00f3n");a.element.tabIndex=0;var e=a.annotation.ye(),f=b.image_url;if(f){var h=a.createElement({F:"div",Ga:["iv-promo-img","iv-click-target"]});f=a.createElement({F:"img",X:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({F:"span",N:"iv-promo-video-duration",qa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({F:"span",N:"iv-promo-playlist-length",qa:b.playlist_length.toString()}),h.appendChild(f));e&&$4(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({F:"a",N:"iv-promo-txt"}),g.yg(f,U4(e)),a.j=f):a.j=a.createElement({F:"div",N:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({F:"p",W:[{F:"strong",
qa:b.text_line_1}]});var m=a.createElement({F:"p",W:[{F:"span",N:"iv-promo-link",qa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({F:"button",Ga:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({F:"button",Ga:["iv-button","iv-promo-button"],W:[{F:"span",N:"iv-button-content",qa:f}]});var p=a.createElement({F:"div",N:"iv-promo-button-container"});p.appendChild(f);e&&$4(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.go(a.j,
"iv-click-target");e&&$4(a,a.j,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({F:"p",W:[{F:"span",qa:b.text_line_1}]}),m=a.createElement({F:"p",W:[{F:"strong",qa:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({F:"span",Ga:["yt-badge","iv-promo-badge-live"],qa:"EN DIRECTO AHORA"})),g.go(a.j,"iv-click-target"),e&&$4(a,a.j,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.j.appendChild(l);m&&a.j.appendChild(m);a.J.appendChild(a.j);
p&&a.J.appendChild(p);c=a.createElement({F:"div",N:"iv-promo-actions"});a.u=a.createElement({F:"button",Ga:["iv-promo-expand","ytp-button"]});a.u.title="Expandir";a.context.j.Ra(a.u,"click",function(q){m2a(a,5E3,q)});
c.appendChild(a.u);g.Jl(a.u,!1);a.context.j.Ra(a.element,"mouseover",a.sZ,a);a.context.j.Ra(a.element,"mouseout",a.rZ,a);a.context.j.Ra(a.element,"touchend",function(q){m2a(a,5E3,q)});
a.B=a.createElement({F:"button",Ga:["iv-promo-close","ytp-button"]});a.B.title="Cerrar";a.context.j.Ra(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.nZ:a.mZ,a);c.appendChild(a.B);g.ho(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.J);a.element.appendChild(c)},m2a=function(a,b,c){c.stopPropagation();
o2a(a);p2a(a,b);a.j.focus()},q2a=function(a){a.isCollapsed||a.S||a.C||(g.go(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},o2a=function(a){a.D.stop();
a.isCollapsed&&(g.jo(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Jl(a.u,!1),g.Jl(a.B,!0))},p2a=function(a,b){a.C||(a.C=g.Nh(function(){r2a(this);
q2a(this)},b,a))},r2a=function(a){a.C&&(g.C.clearTimeout(a.C),a.C=null)},s2a=function(a){this.G=a},W1a=function(a,b,c){b&&(c?l5(a,b.map(function(d){return g.Rn(d,c)})):l5(a,b))},l5=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.r(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.Ww(m,f);d&&(e++,0!==d&&a.G.sendVideoStatsEngageEvent(d,f))},t2a=function(a){g.dO.call(this,a);
var b=this;this.loadNumber=0;this.I={};this.logger=new s2a(this.player);this.D=new g.ZD(this);this.C=this.Fn=null;this.events=new g.ZD(this);this.J=this.j=null;this.S=[];g.M(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.ma("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.ma("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.ma("onShowControls")});
this.D.T(this.player,"resize",function(d){b.ma("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.ma("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.tU,this);this.subscribe("resize",this.DD,this);this.player.V().oa.subscribe("vast_info_card_add",this.xR,this);g.M(this,this.events);this.Z=this.createElement({F:"div",N:"video-custom-annotations"});this.u=new g.W({F:"div",Ga:["ytp-player-content","ytp-iv-player-content"]});g.M(this,this.u);g.CN(this.player,this.u.element,4);this.u.hide();this.B=new g.W({F:"div",Ga:["ytp-iv-video-content"]});g.M(this,this.B);a=this.createElement({F:"div",N:"video-annotations"});
a.appendChild(this.Z);this.B.element.appendChild(a);this.Ot()&&this.load();var c=this.createElement({F:"style"});(g.ah("HEAD")[0]||document.body).appendChild(c);g.cf(this,function(){g.ph(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},u2a=function(a){a=a.createElement({F:"div",
Ga:["annotation","annotation-type-custom"]});g.Jl(a,!1);return a},v2a=function(a,b){b=!b.isCued()&&!g.V(b,1024);
g.ZK(a.u,b);g.ZK(a.B,b)},w2a=function(a,b){for(var c={},d=g.r(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Na(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(w2a(a,e))}return c},A2a=function(a){var b=a.player.getVideoData();
if(b.Ya){var c=a.player.V().oa.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.wu(h)&&h.responseXML?h.responseXML:null)&&x2a(a,h)}};
g.Fv()&&(d.onFinish=y2a(a,d.onFinish));d.postParams={ic_only:"1"};z2a(d,c);g.Cu(b.Ya,d)}}},z2a=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.iy&&(a.postParams.ic_coll=b.iy);b.QB&&(a.postParams.ic_xml=b.QB);b.PA&&(a.postParams.ic_track=b.PA)},B2a=function(a){var b=new g.W({F:"div"});
g.Jl(b.element,!1);var c=new R1a(a.player,b.element,m5(a));g.M(c,b);b.Ca(a.u.element);c.yA();return c},m5=function(a){if(!a.J){var b=new K4(a);
g.M(a,b);var c=new g.Qj(a);g.M(a,c);a.J=new k2a(b,c,a.player.V(),a.player.getVideoData(),a.logger,a.player,a.xg)}return a.J},x2a=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Bz();if(e){var f=g.Az();f&&g.Fz(void 0,e,f,[g.uz(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=w2a(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=T4(f.type,C2a),p=T4(f.style,D2a),q=A1a(f.data),u=0!==q.length?JSON.parse(q):{};var w=f.action;f=G1a;if(null==w)var y=null;else if(g.Ma(w)){l=[];for(var A=g.r(w),B=A.next();!B.done;B=A.next()){var D=f(B.value);
D&&l.push(D)}y=l}else{var G=f(w);y=G?[G]:[]}e=m&&n?new H1a(m,n,p,y,u):null}else e=null}catch(Q){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var F=u2a(f),I=null;switch(l.type){case "branding":if(f.player.V().Rc)break;f.u.element.appendChild(F);I=new k5(F,m5(f),l);break;case "promotion":g.CN(f.player,F,4),I=new l2a(F,m5(f),l)}I&&I.yA();if(f=I)g.M(a,f),a.I[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=B2a(a),g.M(a,a.j));if("card"===e.type){c=a.j;var O=e&&e.data&&e.data.card_type;
f=e.data;if(O)switch(l=f.tracking||{},l={impression:l.impression,click:l.click,close:l.close,NS:l.teaser_impression,EE:l.teaser_click},F=f.tracking_params||{},I=null,O){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,xm:F.card?g.uz(F.card):null,Ej:F.teaser?g.uz(F.teaser):null,sf:F.icon?g.uz(F.icon):null,
channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:V4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};d5(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,
xm:F.card?g.uz(F.card):null,Ej:F.teaser?g.uz(F.teaser):null,sf:F.icon?g.uz(F.icon):null,KA:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:V4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};d5(c,e);break;case "productListing":f.signin_url&&(I=V4({target:"current",value:f.signin_url}));O=[];for(var L=f.offers||[],P=0;P<L.length;P++)O.push(new N1a(g.Vg(L[P].merchant),
g.Vg(L[P].price)));e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,xm:F.card?g.uz(F.card):null,Ej:F.teaser?g.uz(F.teaser):null,sf:F.icon?g.uz(F.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,gy:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:V4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),L3a:I,K3a:f.signin_title?f.signin_title:void 0,J3a:f.signin_message?f.signin_message:void 0,offers:O,onClickCommand:null};d5(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,xm:F.card?g.uz(F.card):
null,Ej:F.teaser?g.uz(F.teaser):null,sf:F.icon?g.uz(F.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,gy:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:V4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};d5(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,xm:F.card?g.uz(F.card):null,Ej:F.teaser?g.uz(F.teaser):null,sf:F.icon?g.uz(F.icon):null,KA:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:V4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},d5(c,e)}}else S1a(a.j,e);c=
!0}}c&&(D4(a.player),a.DD())},E2a=function(a,b){var c=!1;
a.j||(a.j=B2a(a),g.M(a,a.j));for(var d=g.r(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(T1a(a.j,e.cardRenderer),c=!0);c&&(c=a.j,d=b.headerText?g.zA(b.headerText):"",g.sh(c.Kb,d),c.S&&c.S.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ia=b.trackingParams?g.uz(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.uz(b.closeButton.infoCardIconRenderer.trackingParams):null,c.sf=b.icon.infoCardIconRenderer.trackingParams?
g.uz(b.icon.infoCardIconRenderer.trackingParams):null,D4(a.player),a.DD())},F2a=function(a,b,c,d,e){if(!a.player.V().Rc){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new D1a("openUrl","click",new B1a("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.zA(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.zA(b.subscriberCountText))):(b.subscriberCountText&&(e=g.zA(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.zA(b.subscriberCountWithSubscribeText)));var m,n,p=(null==(l=b.signInEndpoint)?void 0:
null==(m=l.commandMetadata)?void 0:null==(n=m.webCommandMetadata)?void 0:n.url)||"";l={subscribeText:g.zA(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.zA(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=l}f=new H1a(c,"branding","branding",f,d);l=u2a(a);a.u.element.appendChild(l);f=new k5(l,m5(a),f);f.yA();g.M(f,f);a.I[c]=f}},y2a=function(a,b){return function(){var c=
g.ya.apply(0,arguments);
a.isDisposed()||a.S.push(g.Un.Kh(function(){b.apply(null,g.t(c))}))}},G2a=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.vN.prototype.Pw=g.ba(17,function(a,b){var c=g.vO(this.ub());c&&c.Pw(a,b)});
var F4={},G4=null;g.Va(I4,g.so);g.k=I4.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.u;else if(this.Sc())return!1;H4(this);this.startTime=a=g.Ua();-1==this.j&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.zD();this.Yj("play");-1==this.j&&this.Yj("resume");this.j=1;var b=g.Pa(this);b in F4||(F4[b]=this);g1a();h1a(this,a);return!0};
g.k.stop=function(a){H4(this);this.j=0;a&&(this.progress=1);i1a(this,this.progress);this.Yj("stop");this.Uz()};
g.k.pause=function(){this.Sc()&&(H4(this),this.j=-1,this.Yj("pause"))};
g.k.ra=function(){0==this.j||this.stop(!1);this.Yj("destroy");I4.Qe.ra.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.qF=function(){this.Yj("animate")};
g.k.Yj=function(a){this.dispatchEvent(new j1a(a,this))};
g.Va(j1a,g.df);g.Va(J4,I4);J4.prototype.C=function(){};
J4.prototype.qF=function(){this.C();J4.Qe.qF.call(this)};
J4.prototype.Uz=function(){this.C();J4.Qe.Uz.call(this)};
J4.prototype.zD=function(){this.C();J4.Qe.zD.call(this)};
g.Va(k1a,J4);k1a.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var g5=new g.Yo("browseEndpoint");g.v(K4,g.K);K4.prototype.Ra=function(a,b,c,d){c=(0,g.Qa)(c,d||this.u);a=g.Ax(a,b,c);this.j.push(a);return a};
K4.prototype.jD=function(a,b,c,d){c=(0,g.Qa)(c,d||this.u);a=g.Foa(a,b,c);this.j.push(a);return a};
K4.prototype.yc=function(a){g.Bx(a);g.ac(this.j,a)};
K4.prototype.ra=function(){g.Bx(this.j);this.j.length=0;g.K.prototype.ra.call(this)};g.v(n1a,g.dO);g.k=n1a.prototype;g.k.load=function(){g.dO.prototype.load.call(this);if(!N4(this)){var a=g.QBa(this.player.getVideoData());a?(a=m1a(a,o1a(this)),O4(this,a,!1)):p1a(this)}};
g.k.unload=function(){O4(this,null);this.B&&(this.B.abort(),this.B=null);g.dO.prototype.unload.call(this)};
g.k.Cg=function(a,b){return N4(this)?"loadCustomEndscreenRenderer"===a?(a=m1a(b,"new"),O4(this,a),!0):null:null};
g.k.getOptions=function(){return N4(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Bb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<H2a.length;f++){var h=Math.abs(b.width-H2a[f]);if(-1===e||d>=h)e=f,d=h}d=I2a[e];this.u&&g.xl(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Hl(e.element,m,f);g.Dl(e.element,n,p);this.ea&&(g.jo(e.element,J2a),256<m||256<f?g.go(e.element,"ytp-ce-large-round"):96<m||96<f?g.go(e.element,"ytp-ce-medium-round"):g.go(e.element,"ytp-ce-small-round"));g.jo(e.element,K2a);m=h.left+h.width/2;h=h.top+l/2;g.go(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.jo(e.element,I2a);g.go(e.element,d);(e=g.bh(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.xl(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())S4(this,this.endscreen.impressionUrls),(a=g.Bz())&&this.endscreen.visualElement&&g.Gz(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.D[a];g.go(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.go(b,"ytp-ce-shown");S4(this,c.impressionUrls);(b=g.Bz())&&g.Gz(b,c.visualElement);this.player.V().C&&this.player.Pa("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.io(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.io(b,"ytp-ce-shown");this.player.V().C&&this.player.Pa("endscreenelementhidden",a)}};
g.k.C3=function(a){var b=this;a.target===window&&(new g.Yn(function(){for(var c=g.r(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.jo(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var H2a=[346,426,470,506,570,640,853,1280,1920],I2a="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),K2a=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],J2a=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var C1a={fla:"current",DFa:"new"};var E1a={CLOSE:"close",dJa:"openUrl",SUBSCRIBE:"subscribe"},F1a={qga:"click",CLOSE:"close",ksa:"hidden",nOa:"rollOut",oOa:"rollOver",gQa:"shown"};H1a.prototype.ye=function(){var a=I1a(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var D2a={eca:"anchored",RT:"branding",CHANNEL:"channel",Tka:"cta",nsa:"highlightText",fwa:"label",PLAYLIST:"playlist",VLa:"popup",JSa:"speech",SUBSCRIBE:"subscribe",FVa:"title",VIDEO:"video",T0a:"website"},C2a={RT:"branding",tea:"card",hna:"drawer",msa:"highlight",FBa:"marker",VMa:"promotion",TEXT:"text",D1a:"widget"};g.v(Z4,g.K);g.k=Z4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.sA(a,b,{id:c,namespace:"annotations_module"});d&&this.Ya.set(a,d);e&&this.fb.set(a,e);this.context.G.qe([a])};
g.k.yA=function(){this.context.u.subscribe("resize",this.KB,this)};
g.k.rF=function(a,b,c,d,e,f){if(this.yb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.ph(this.element)};
g.k.KB=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=U4(a);if(f){var h=P1a(f,a.target),l=function(){a.j&&e.context.G.pauseVideo();var m=e.context.videoData.C||!1,n=g.nu(f||"");m&&n&&(n.v||n.list)?e.context.G.Ll(n.v,b,n.list,!1):g.kM(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);l5(this.context.logger,c,l,d);O1a(f)||(c=g.Bz(),d=b.itct,c&&d&&g.Lz(c,g.uz(d)))}};
g.k.ra=function(){this.Ya.clear();this.fb.clear();g.K.prototype.ra.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.M(this,a);return a.element};g.v(R1a,Z4);g.k=R1a.prototype;g.k.Yp=function(){this.oa&&d5(this,this.oa)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.G.getRootNode())?(a=g.Il(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.KB=function(){var a=this.isAvailable();g.Jl(this.element,a);g.ko(this.context.G.getRootNode(),g.qT.IV_DRAWER_ENABLED,a);D4(this.G)};
g.k.destroy=function(){this.G.Pw(!1);try{this.G.getRootNode().removeChild(this.C)}catch(a){}g.Vx(this.ea);g.Bx(this.xa);this.Va&&this.Va.dispose();this.D&&this.D.dispose();Z4.prototype.destroy.call(this)};
g.k.eY=function(){if(this.B){l5(this.context.logger,i5(this).tracking.close);var a=g.Bz();a&&this.J&&g.Lz(a,this.J);c5(this)}};
g.k.xY=function(){g.ko(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.q_=function(){var a=g.Bz(),b=i5(this);b=b?b.sf:this.sf;a&&b&&g.Jz(a,[b])};
g.k.p_=function(){var a=g.Bz(),b=i5(this);b=b?b.sf:this.sf;a&&b&&g.Kz(a,[b])};
g.k.sU=function(){var a=i5(this);l5(this.context.logger,a.tracking.NS);var b=g.Bz();b&&a&&g.Jz(b,[a.Ej,a.sf])};
g.k.s_=function(){var a=g.Bz(),b=i5(this);a&&b&&g.Kz(a,[b.Ej])};
g.k.rU=function(a){var b=i5(this),c=g.Bz();this.j?a?(a=this.context.logger,l5(a,b.tracking.EE),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.Ej&&g.Lz(c,b.Ej)):(a=this.context.logger,l5(a,b.tracking.EE),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.sf&&g.Lz(c,b.sf)):(a=this.context.logger,l5(a,b.tracking.EE),a.G.sendVideoStatsEngageEvent(4,void 0),c&&this.sf&&g.Lz(c,this.sf))};g.v(j5,Z4);j5.prototype.yA=function(){Z4.prototype.yA.call(this);f2a(this)};
j5.prototype.show=function(){Z4.prototype.show.call(this);var a=g.Bz(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Jz(a,[g.uz(b.itct)])};
j5.prototype.hide=function(){Z4.prototype.hide.call(this);var a=g.Bz(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Kz(a,[g.uz(b.itct)])};g.v(k5,j5);
k5.prototype.show=function(){if(!this.isActive){j5.prototype.show.call(this);if(!this.J){g.go(this.element,"iv-branding");var a=this.annotation.data;this.u=this.createElement({F:"img",Ga:["branding-img","iv-click-target"],X:{"aria-label":"Marca de agua del canal",src:a.image_url,width:a.image_width,height:a.image_height}});g.Jl(this.u,!1);var b=this.context.Y.K("html5_player_branding_button_killswitch")?this.createElement({F:"div",Ga:["branding-img-container"]}):this.createElement({F:"button",Ga:["branding-img-container",
"ytp-button"]});b.appendChild(this.u);this.element.appendChild(b);var c=this.annotation.ye();c&&(b=this.context.Y.K("html5_player_branding_button_killswitch")?this.u:b,$4(this,b,c,this.annotation.id,a.session_data));j2a(this,a);this.J=!0}g.Jl(this.element,!0);this.isActive=!0;this.u&&g2a(this,this.u)}};
k5.prototype.hide=function(){this.isActive&&(j5.prototype.hide.call(this),g.Jl(this.element,!1),this.isActive=!1)};
k5.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);j5.prototype.destroy.call(this)};g.v(l2a,j5);g.k=l2a.prototype;g.k.show=function(){this.isActive||(j5.prototype.show.call(this),this.Z||(n2a(this),this.Z=!0),g.Jl(this.element,!0),g.Nh(function(){g.io(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,r2a(this),o2a(this),p2a(this,this.I))};
g.k.hide=function(){this.isActive&&(g.go(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.rF=function(a,b,c,d,e,f){return this.isCollapsed?!1:j5.prototype.rF.call(this,a,b,c,d,e,f)};
g.k.sZ=function(a){this.S=!0;m2a(this,500,a)};
g.k.rZ=function(){this.S=!1;q2a(this)};
g.k.mZ=function(a){a.stopPropagation();this.hide()};
g.k.nZ=function(a){a.stopPropagation();r2a(this);this.isCollapsed=!0;g.go(this.element,"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();j5.prototype.destroy.call(this)};g.v(t2a,g.dO);g.k=t2a.prototype;g.k.Cg=function(a,b){if(!G2a(this.player.V().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.GXa(b))&&x2a(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(V1a(this.j,b),D4(this.player)),!0}return null};
g.k.getOptions=function(){return G2a(this.player.V().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Ot=function(){var a=this.player.V(),b=this.player.getVideoData();return b.C&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.dT||a.oa.get(b.videoId)||g.pI(b)||g.qI(b)?!0:!1};
g.k.DD=function(){if(this.B){var a=this.player.gb().getVideoContentRect(!0);g.Hl(this.B.element,a.width,a.height);g.Dl(this.B.element,a.left,a.top)}if(this.j){var b=this.player.dk();a=this.j;b=b.width;g.ko(a.C,"iv-drawer-small",426>=b);g.ko(a.C,"iv-drawer-big",1280<=b)}};
g.k.tU=function(a){v2a(this,a.state);g.V(a.state,2)&&(this.Ai()&&this.wm()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Pw(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.C=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.wu(h)&&h.responseXML?h.responseXML:null)&&(x2a(b,h),g.go(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.dO.prototype.load.call(this);v2a(this,this.player.Db());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.Fv()&&(a=y2a(this,a));var e={format:"XML",onFinish:a,onError:function(){b.C=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.V().oa.get(d);f&&z2a(e,f);f=f&&(f.QB||f.iy);if(!c.Ut||f)c.Ya?this.C=g.Cu(c.Ya,e):(this.Fn=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.Fn));
g.CN(this.player,this.B.element,4);this.DD();(f=g.pI(c))&&E2a(this,f);(f=g.qI(c))&&f.featuredChannel&&F2a(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Ya&&(this.Fn&&(this.player.removeEventListener("videodatachange",this.Fn),this.Fn=null),this.C=g.Cu(b.Ya,a))};
g.k.unload=function(){this.player.Ff("annotations_module");for(var a=g.r(Object.keys(this.I)),b=a.next();!b.done;b=a.next())this.I[b.value].destroy();this.J=null;this.j&&(this.j.destroy(),this.j=null,D4(this.player));this.C&&(this.C.abort(),this.C=null);this.I={};this.u.hide();g.dO.prototype.unload.call(this);this.B.detach();this.Fn&&(this.player.removeEventListener("videodatachange",this.Fn),this.Fn=null)};
g.k.xR=function(a){a===this.player.getVideoData().videoId&&(this.loaded?A2a(this):this.load())};
g.k.Ai=function(){return!!this.j&&this.j.isAvailable()};
g.k.wm=function(){return!!this.j&&this.j.B};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Ai();this.j&&(a?c?b5(this.j,c,b):b5(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):c5(this.j))};
g.k.Pw=function(a,b){this.player.ma(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ra=function(){this.player.V().oa.unsubscribe("vast_info_card_add",this.xR,this);g.io(this.player.getRootNode(),g.qT.IV_DRAWER_OPEN);for(var a=this.S,b=g.Un,c=0,d=a.length;c<d;c++)b.Yk(a[c]);this.S.length=0;g.dO.prototype.ra.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.M(this,a);return a.element};g.cO("annotations_module",t2a);g.cO("creatorendscreen",n1a);})(_yt_player);
