(function(g){var window=this;'use strict';var M2a=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},N2a=function(a){return g.mG(a)&&!a.K("web_player_i_see_captions_3_killswitch")},O2a=function(a,b){var c=new g.JG;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.j=a.j;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},P2a=function(a,b){var c,d,e;
return g.z(function(f){if(1==f.j)return c=a+"|"+b,g.x(f,g.Cw(),2);if(3!=f.j){d=f.u;if(!d)throw g.aw("gct");return g.x(f,g.vH(d),3)}e=f.u;return f.return(e.get("captions",c))})},Q2a=function(a,b,c){P2a(a,b).then(function(d){d&&c(d.trackData,new g.JG(d.metadata))})},T2a=function(a){if(!R2a.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(S2a,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]},p5=function(){this.segments=[]},U2a=function(a,b){var c=g.lc(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.Yb(a.segments,c),g.Yb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.ic(a.segments,c,0,b),g.ic(a.segments,c+1,0,b)))},V2a=function(a,b,c,d,e,f){g.K.call(this);
this.policy=a;this.player=b;this.ea=c;this.S=d;this.D=e;this.Z=f;this.Y=this.player.V();this.C=new p5;this.I=-1;this.B=this.u=this.j=null;this.J=new g.Yn(this.iQ,1E3,this);this.events=new g.ZD(this);g.M(this,this.J);g.M(this,this.events);this.events.T(b,"SEEK_COMPLETE",this.zw);this.zw();this.iQ()},W2a=function(a){return a.j&&a.j.B?a.j.B+a.player.Bd()<a.player.getCurrentTime():!1},X2a=function(a,b){var c=g.uD(b,a.policy,{}).ye(),d={format:"RAW",
withCredentials:!0};a.D&&(d.responseType="arraybuffer");a.B=g.Fu(c,d,3,100).then(function(e){a:{e=e.xhr;a.isDisposed();if(a.u){var f=!(a.D?e.response:e.responseText)||400<=e.status,h=g.Hxa(e);if(h){e=g.uD(a.u,a.policy,{});a.u.ek(e,h);X2a(a,a.u);break a}f?a.player.va("capfail",{status:e.status}):(a.player.lj().ap("fcb_r"),h=a.u.j[0].Na,null!=a.S&&a.I!==h&&(f=a.u.j[0],a.D?a.S(e.response,1E3*(f.startTime+a.player.Bd())):a.S(e.responseText,1E3*(f.startTime+a.player.Bd())),a.I=h))}a.u=null;a.B=null}}).bj(function(e){a.u=
null;
a.B=null;var f;a.player.va("capfail",{status:null==(f=e.xhr)?void 0:f.status})});
a.u=b;U2a(a.C,a.u.j[0].Na)},q5=function(a,b){g.gO.call(this,b.V());
this.u=a;this.G=b;this.B=null;this.D=!1;this.I=g.oG(this.G.V())&&!this.u.isManifestless},Z2a=function(a,b){var c=[],d;
for(d in a.u.j)if(a.u.j.hasOwnProperty(d)){var e=a.u.j[d];if(g.jO(e,b||null)){var f=e.info.id,h=f,l="."+f,m="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind;else{e=f;var n=g.N0a.get(e);null==n&&(n=Y2a[e]||Y2a[e.replace(/-/g,"_")],g.N0a.set(e,n));h=n||h}c.push(new g.JG({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},$2a=function(a,b){return null!=b&&b in a.u.j?a.u.j[b]:null},a3a=function(a,b,c){var d=
[],e;
for(e in a.u.j)if(a.u.j.hasOwnProperty(e)){var f=a.u.j[e];if(g.jO(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},r5=function(a,b,c,d,e,f,h,l){var m={};
Object.assign(m,b);Object.assign(m,a.params);Object.assign(m,c);var n={};Object.assign(n,b.Wd);a.params.Wd&&Object.assign(n,a.params.Wd);Object.assign(n,c.Wd);m.Wd=n;g.W.call(this,{F:"div",N:"caption-window",X:{id:"caption-window-"+a.id,dir:1===m.lh?"rtl":"ltr",tabindex:"0",lang:m.lang},W:[{F:"span",N:"captions-text",X:{style:"word-wrap: normal; display: block;"}}]});this.D=[];this.Ba=!1;this.u=a;this.La=this.Ia=null;this.playerWidth=f;this.playerHeight=h;this.I=null;this.maxWidth=.96*f;this.Ya=.96*
h;this.j=m;this.Rb=c;this.ea=b;this.C=this.Da("captions-text");this.Gb=""!==this.C.style.getPropertyValue("box-decoration-break")||""!==this.C.style.getPropertyValue("-webkit-box-decoration-break");this.oa=e/360*16;!l.jb("web_player_scale_font_size_for_shorts_killswitch")&&e>=d&&(this.oa=f/640*16);this.type=0;this.fb=this.oa*b3a(n);a=new g.gz(this.element,!0);g.M(this,a);a.subscribe("dragstart",this.wU,this);a.subscribe("dragmove",this.vU,this);a.subscribe("dragend",this.uU,this);this.ob=this.kb=
0;b="";this.j.windowOpacity&&(a=T2a(this.j.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.j.windowOpacity+")");a={"background-color":b,display:!1===this.j.isVisible?"none":"","text-align":c3a[this.j.textAlign]};this.Gb&&(a["border-radius"]=b?this.fb/8+"px":"");if(this.B=2===this.u.params.lh||3===this.u.params.lh)b=this.element,c="vertical-rl",1===this.j.hL&&(c="vertical-lr"),g.Dc&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.xl(b,"-o-writing-mode",c),g.xl(b,"-webkit-writing-mode",c),g.xl(b,"writing-mode",
c),g.xl(b,"text-orientation","upright"),g.go(b,"ytp-vertical-caption"),3===this.u.params.lh&&(g.xl(b,"text-orientation",""),g.xl(b,"transform","rotate(180deg)"));g.xl(this.element,a);switch(this.j.Vj){case 0:case 1:case 2:g.go(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.go(this.element,"ytp-caption-window-bottom")}},b3a=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},d3a=function(a,b){var c={},d=b.background?b.background:a.j.Wd.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.j.Wd.backgroundOpacity;d=T2a(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Gb&&(c["box-decoration-break"]="clone",c["border-radius"]=a.fb/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.oa*b3a(b)+"px";d=1;e=b.color||a.j.Wd.color;if(b.color||null!=b.textOpacity)e=T2a(e),d=null==b.textOpacity?a.j.Wd.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.PG&&(h=e=b.PG);var l=a.oa/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.Qu()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.j.Wd.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.italic&&(c["font-style"]=
"italic");b.underline&&(c["text-decoration"]="underline");b.NZ&&(c.visibility="hidden");1===b.FP&&a.B&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.sG||g.Zv,3===a.u.params.lh?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.Fl||2===b.Fl||3===b.Fl||4===b.Fl||5===b.Fl)if(g.sG)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Fl){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},e3a=function(a){a.I=g.ih("SPAN");
g.xl(a.I,{display:"block"});g.go(a.I,"caption-visual-line");a.C.appendChild(a.I)},f3a=function(a,b){var c=g.ih("SPAN");
g.xl(c,{display:"inline-block","white-space":"pre-wrap"});g.xl(c,d3a(a,b));c.classList.add("ytp-caption-segment");a.I.appendChild(c);c.previousElementSibling&&(g.xl(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.xl(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},g3a=function(a,b,c){a.Ba=a.Ba||!!c;
var d={};Object.assign(d,a.j.Wd);Object.assign(d,c||b.j);Object.assign(d,a.Rb.Wd);(c=!a.I)&&e3a(a);for(var e=a.Ia&&a.La&&g.Ef(d,a.La)?a.Ia:f3a(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(e3a(a),e=f3a(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.mh(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.sG||!g.zl(n.children[2],"text-emphasis")||(m=a.B?"padding-right":"padding-top",g.zl(n.children[2],"text-emphasis-position")&&(m=
a.B?"padding-left":"padding-bottom"),g.kf?g.xl(e,m,"1em"):g.xl(e,m,"0.5em")))}a.La=d;a.Ia=e;a.D.push(b)},s5=function(a,b,c,d){g.gO.call(this,a);
this.videoData=b;this.audioTrack=c;this.Wa=d;this.C=b.NG},t5=function(a,b,c,d,e,f,h,l){r5.call(this,a,b,c,d,e,f,h,l);
this.type=1},u5=function(a,b,c,d,e,f,h,l){r5.call(this,a,b,c,d,e,f,h,l);
this.type=2;this.J=[];this.Z=this.S=this.Qa=0;this.xa=NaN;this.yb=0;this.Kb=null;this.Va=new g.Yn(this.D2,433,this);g.go(this.element,"ytp-caption-window-rollup");g.M(this,this.Va);g.xl(this.element,"overflow","hidden")},h3a=function(a,b){if(!b)return"";
a.B&&1!==a.u.params.hL&&(b*=-1);return"translate"+(a.B?"X":"Y")+"("+b+"px)"},i3a=function(a){a.J=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.u.params.So,c=0,d=0,e=a.J.length-1;c<b&&-1<e;){var f=a.J[e];d+=a.B?f.offsetWidth:f.offsetHeight;c++;e--}a.J.length<b&&(d*=b/a.J.length);a.S=d;b=Math;c=b.max;isNaN(a.xa)&&((d=a.j.Bp)?(e=g.ih("SPAN"),g.sh(e,"\u2013".repeat(d)),g.xl(e,d3a(a,a.j.Wd)),a.C.appendChild(e),a.xa=e.offsetWidth,a.C.removeChild(e)):a.xa=0);d=a.C;a.Z=c.call(b,a.xa,a.yb,(a.B?d.offsetHeight:d.offsetWidth)+1)},j3a=function(a,b){i3a(a);
var c=a.J.reduce(function(e,f){return(a.B?f.offsetWidth:f.offsetHeight)+e},0);
c=a.S-c;if(c!==a.Qa){var d=0<c&&0===a.Qa;b||isNaN(c)||d||(g.go(a.element,"ytp-rollup-mode"),g.Zn(a.Va));g.xl(a.C,"transform",h3a(a,c));a.Qa=c}i3a(a)},v5=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.sA.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.j=h},w5=function(a,b,c,d,e){g.sA.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.j=[]},k3a=function(a){var b="_"+x5++;
return new w5(0,0x8000000000000,0,b,a)},m3a=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.gf){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=l3a(l.textContent,n.textContent,p.textContent,f.textContent,h);return new v5(a,b,e,c,l,d,m)}switch(m.gf){case 9:case 10:m.Fl=1;break;case 11:m.Fl=2;break;case 12:m.Fl=3;break;case 13:m.Fl=4;break;case 14:m.Fl=5}return new v5(a,b,e,c,l.textContent||"",d,m)},l3a=function(a,b,c,d,e){var f=g.Qu(),h=
f?g.ih("DIV"):g.ih("RUBY"),l=g.ih("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.ih("DIV"):g.ih("RP");a.textContent=b;h.appendChild(a);b=f?g.ih("DIV"):g.ih("RT");b.textContent=c;h.appendChild(b);c=e.gf;if(10===c||11===c||12===c||13===c||14===c)if(g.xl(b,"text-emphasis-style","filled circle"),g.xl(b,"text-emphasis-color","currentcolor"),g.xl(b,"webkit-text-emphasis","filled circle"),11===e.gf||13===e.gf)g.xl(b,"webkit-text-emphasis-position","under left"),g.xl(b,"text-emphasis-position","under left");c=!0;if(4===e.gf||7===e.gf||12===e.gf||
14===e.gf)g.xl(h,"ruby-position","over"),g.xl(h,"-webkit-ruby-position","before");else if(5===e.gf||6===e.gf||11===e.gf||13===e.gf)g.xl(h,"ruby-position","under"),g.xl(h,"-webkit-ruby-position","after"),c=!1;e=f?g.ih("DIV"):g.ih("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.xl(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.xl(f,"display","none"),f=f.nextElementSibling,g.xl(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.xl(h.lastElementChild,"display","none"),d?(g.xl(h,"padding-top","0.6em"),g.xl(f,"top","0")):(g.xl(h,"padding-bottom","0.6em"),g.xl(f,"bottom","0")));return h},y5=function(){g.K.apply(this,arguments)},z5=function(a){y5.call(this);
this.C=a;this.pens={};this.S={};this.Z={};this.D="_"+x5++;this.J={};this.B=this.j=null;this.I=!0},A5=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},B5=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},C5=function(a,b){a=A5(a,b);
return void 0!==a?a:null},E5=function(a,b){a=a.getAttribute(b);
if(null!=a)return D5.test(a),a},n3a=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.Z[d]:a.C);a=C5(b,"mh");null!=a&&(c.ww=a);a=C5(b,"ju");null!=a&&(c.textAlign=a);a=C5(b,"pd");null!=a&&(c.lh=a);a=C5(b,"sd");null!=a&&(c.hL=a);a=E5(b,"wfc");null!=a&&(c.windowColor=a);b=A5(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},o3a=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.S[d]);a=C5(b,"ap");null!=a&&(c.Vj=a);a=A5(b,"cc");null!=a&&(c.Bp=a);a=A5(b,"ah");null!=a&&(c.Pi=a);a=A5(b,"rc");null!=a&&(c.So=a);b=A5(b,"av");null!=b&&(c.Gl=b);return c},p3a=function(a,b,c,d){var e={};
Object.assign(e,o3a(a,b));Object.assign(e,n3a(a,b));d?g.Ef(e,a.C)?(d=a.D,e=a.C):d="_"+x5++:d=b.getAttribute("id")||"_"+x5++;a=A5(b,"t")+c;b=A5(b,"d")||0x8000000000000;if(2===e.lh||3===e.lh)c=e.So,e.So=e.Bp,e.Bp=c;return new w5(a,b,0,d,e)},F5=function(a){y5.call(this);
this.I=a;this.j=new Map;this.C=new Map;this.D=new Map;this.B=new Map},G5=function(a){a=g.Bg(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},q3a=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.C.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.D.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.So=a);b=b.ccColCount;void 0!==b&&(f.Bp=b);if(2===f.lh||3===f.lh)b=f.So,f.So=f.Bp,f.Bp=b;return new w5(c,d,0,e,f)},s3a=function(){this.B=this.time=this.mode=this.u=0;
this.C=new r3a(this);this.D=new r3a(this);this.j=[];this.clear()},u3a=function(a,b,c){if(255===a&&255===b||!a&&!b)return{Lr:a,
yp:b,result:0};a=t3a[a];b=t3a[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.yp===d;if(d)return{Lr:a,yp:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Lr:a,yp:b,result:2};return{Lr:a,yp:b,result:3}},w3a=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.B&&a.reset(),a.C.u.clear(),a.D.u.clear()):(a.B=0,v3a(a.C,b,c,d))},x3a=function(a,b){a.j.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.r(a.j),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?w3a(a,d.dO,d.eO,b):1===d.type&&a.u&496&&v3a(a.D,d.dO,d.eO,b);a.j.length=0},H5=function(){this.type=0},I5=function(){this.state=this.yp=this.Lr=0},y3a=function(){this.timestamp=this.j=0},J5=function(a){this.D=a;
this.B=[];this.j=this.u=this.row=0;this.style=new H5;for(a=this.C=0;15>=a;a++){this.B[a]=[];for(var b=0;32>=b;b++)this.B[a][b]=new y3a}},K5=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.D.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var q=a.B[m][p];
if(0!==q.j){0===c&&(c=m,d=p);n=String.fromCharCode(q.j);var u=q.timestamp;u<e&&(e=u);q.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===q.j||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.C(c,d,e,l,f)}else for(d=c=0,f=e=a.D.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.B[h][m],q=p.j,0!==q&&(0===c&&(c=h,d=m),n=String.fromCharCode(q),u=p.timestamp,u<=e&&(e=u),l+=n,p.reset()),32===m||0===q)l&&b.C(c,d,e,f,l),e=f,l="",d=c=0},D3a=function(a,b){switch(a){case 0:return z3a[(b&127)-32];
case 1:return A3a[b&15];case 2:return B3a[b&31];case 3:return C3a[b&31]}return 0},L5=function(a){return a.B[a.row][a.u]},M5=function(a,b,c){2<=b&&1<a.u&&(--a.u,L5(a).j=0);
var d=L5(a);d.timestamp=a.D.time+0;d.j=D3a(b,c);32>a.u&&a.u++},E3a=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.B[b+e][f],l=a.B[c+e][f];
h.j=l.j;h.timestamp=l.timestamp}},N5=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.B[b+d][e].reset()},F3a=function(a){a.row=0<a.j?a.j:1;
a.u=1;N5(a,0,15)},G3a=function(a){this.B=a;
this.D=0;this.style=new H5;this.I=new J5(this.B);this.J=new J5(this.B);this.text=new J5(this.B);this.u=this.I;this.C=this.J;this.j=this.u},H3a=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.j||(K5(d,c),F3a(a.u),F3a(a.C),d.row=15,d.j=b,e=!0)}a.style.set(3);a.j=d;a.j.style=a.style;a.B.mode=1<<d.C;e?d.u=1:d.j!==b&&(d.j>b?(K5(d,c),N5(d,d.row-d.j,b)):d.row<b&&(b=d.j),d.j=b)},I3a=function(a){a.style.set(1);
a.j=a.C;a.j.j=0;a.j.style=a.style;a.B.mode=1<<a.j.C},J3a=function(a){a.style.set(4);
a.j=a.text;a.j.style=a.style;a.B.mode=1<<a.j.C},r3a=function(a){this.j=a;
this.D=0;this.B=new G3a(this.j);this.I=new G3a(this.j);this.u=new I5;this.C=this.B},v3a=function(a,b,c,d){a.u.update();
b=u3a(b,c,a.u);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Lr;c=b.yp;if(32<=e||!e)a.j.mode&a.j.u&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.C.j,b&96&&M5(a,0,b),c&96&&M5(a,0,c),0!==b&&0!==c&&3===a.style.type&&K5(a,d));else if(e&16)a:if(!a.u.matches(e,c)&&(b=a.u,b.Lr=e,b.yp=c,b.state=2,b=e&8?a.I:a.B,a.C=b,a.j.mode=1<<(a.D<<2)+(b.D<<1)+(4===b.style.type?1:0),(a.j.mode|1<<(a.D<<2)+(b.D<<1)+(4!==b.style.type?1:0))&a.j.u))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.j;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.j&&(d=c.j,d===c.row))break;var f=1+c.row-c.j,h=1+d-c.j;E3a(c,h,f,c.j);b=f;e=c.j;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));N5(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:M5(b.j,0,32);break a;case 48:57===c?(d=b.j,L5(d).j=0,32>d.u&&d.u++):M5(b.j,1,c&15)}break;case 2:c&32&&M5(b.j,2,c&31);break;case 3:c&32&&M5(b.j,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:I3a(b);
break;case 33:d=b.j;1<d.u&&(--d.u,L5(d).j=0);break;case 36:d=b.j;b=L5(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.B[a][c]===b){for(;32>=c;c++)d.B[a][c].reset();break}break;case 37:H3a(b,2,d);break;case 38:H3a(b,3,d);break;case 39:H3a(b,4,d);break;case 40:M5(b.j,0,32);break;case 41:b.style.set(2);b.j=b.u;b.j.j=0;b.j.style=b.style;b.B.mode=1<<b.j.C;break;case 42:d=b.text;d.j=15;d.style.set(4);F3a(d);J3a(b);break;case 43:J3a(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:K5(a,d)}N5(a,
0,15);break;case 45:b:{a=b.j;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.j&&(a.j=2,a.row<a.j&&(a.row=a.j));b=a.row-a.j+1;K5(a,d);E3a(a,b,b+1,a.j-1);N5(a,a.row,1)}break;case 46:N5(b.C,0,15);break;case 47:K5(b.u,d),b.C.updateTime(b.B.time+0),d=b.C,b.C=b.u,b.u=d,I3a(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.j,32<(d.u+=c&3)&&(d.u=32)}}},K3a=function(){},O5=function(a,b,c){this.trackData=a;
this.I=c;this.version=this.D=this.B=this.byteOffset=0;this.j=new DataView(this.trackData);this.u=[]},P5=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.j.getUint8(b)},Q5=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.j.getUint32(b)},R5=function(a,b){y5.call(this);
this.B=a;this.C=b;this.track="CC3"===this.C.languageName?4:0;this.j=new s3a;this.j.u=1<<this.track},M3a=function(a){if("string"===typeof a)return!1;
a=new O5(a,8,0);return L3a(a)},L3a=function(a){if(!(a.byteOffset<a.j.byteLength)||1380139777!==Q5(a))return!1;
a.version=P5(a);if(1<a.version)return!1;P5(a);P5(a);P5(a);return!0},S5=function(){y5.call(this)},N3a=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.italic=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new v5(b,c,d,e.id,p.nodeValue,f||0<n,g.Bf(l)?void 0:l),m.push(p),e.j.push(p);else{var q={};Object.assign(q,l);N3a(a,b,c,d,e,!0,p,q,m)}}},O3a=function(a){var b=a.split(":");
a=0;b=g.r(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},P3a=function(a,b,c,d){d=Object.assign({ww:0},d);
return new w5(a,b,c,"_"+x5++,d)},T5=function(a,b){g.K.call(this);
this.G=a;this.Y=b;this.parser=null;this.j=this.G.Qv()},V3a=function(a,b,c,d,e){d=d||0;
e=e||0;if(a.j&&b){var f=e,h=Q3a(a,b,d),l=[];try{for(var m=g.r(h),n=m.next();!n.done;n=m.next()){var p=n.value,q=p.trackData,u=p.XK;l="string"!==typeof q?l.concat(R3a(a,c,q,u,f)):"WEBVTT"===q.substring(0,6)?l.concat(S3a(a,q,u)):l.concat(T3a(a,c,q,u))}var w=l}catch(y){g.qz(y),a.clear(),w=[]}if(0!==w.length)return w}b=U3a(b);if(!b)return[];try{return"string"!==typeof b?R3a(a,c,b,d,e):"WEBVTT"===b.substring(0,6)?S3a(a,b,d):T3a(a,c,b,d)}catch(y){return g.qz(y),a.clear(),[]}},U3a=function(a){if("string"===
typeof a||M3a(a))return a;
var b=new DataView(a);if(8>=b.byteLength||1718909296!==b.getUint32(4))return"";b=g.wC(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.hC(a)},Q3a=function(a,b,c){if("string"===typeof b||M3a(b))return[{trackData:b,
XK:c}];var d=new DataView(b);if(8>=d.byteLength||1718909296!==d.getUint32(4))return[];var e=g.wwa(d);if(a.j&&e){var f=g.owa(e),h=g.pwa(e);e=e.j;f&&e&&a.j.QA(e,f,h)}f=g.FC(d,1835295092);if(!f||!f.length||!f[0].size)return[];a=[];f=g.r(f.entries());for(h=f.next();!h.done;h=f.next())e=g.r(h.value),h=e.next().value,e=e.next().value,e=new Uint8Array(b,e.dataOffset,e.size-(e.dataOffset-e.offset)),e=g.hC(e),a.push({trackData:e,XK:c+1E3*h});W3a(d,a,c);return a=a.filter(function(l){return!!l.trackData})},
W3a=function(a,b,c){var d=g.wC(a,0,1836476516),e=9E4;
d&&(e=g.xC(d)||9E4);d=0;var f=g.FC(a,1836019558);f=g.r(f.entries());for(var h=f.next();!h.done;h=f.next()){var l=g.r(h.value);h=l.next().value;l=l.next().value;h<b.length&&(l=g.wC(a,l.dataOffset,1953653094))&&(l=g.wC(a,l.dataOffset,1952867444))&&(l=g.DC(l)/e*1E3,0===h&&(d=l),b[h].XK=l-d+c||c*h*1E3)}},R3a=function(a,b,c,d,e){if(!M3a(c))throw Error("Invalid binary caption track data");
a.parser||(a.parser=new R5(e,b));return a.parser.u(c,d)},S3a=function(a,b,c){a.parser||(a.parser=new S5);
a=a.parser.u(b,c);.01>Math.random()&&g.rz(Error("Deprecated subtitles format in web player: WebVTT"));return a},T3a=function(a,b,c,d){if("{"===c[0])try{return a.parser||(a.parser=new F5(X3a(b))),a.parser.u(c,d)}catch(f){return g.qz(f),[]}var e=g.GXa(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if("timedtext"===e.firstChild.tagName){if(3===Number(e.firstChild.getAttribute("format")))return a.parser||(a.parser=new z5(X3a(b),a.Y)),a.parser.u(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if("transcript"===e.firstChild.tagName)throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},X3a=function(a){var b=
{};
if(a=g.MG(a))b.lang=a,g.XYa.test(a)&&(b.lh=1);return b},U5=function(a){g.dO.call(this,a);
var b=this;this.G=a;this.Y=this.G.V();this.videoData=this.G.getVideoData();this.ob=this.G.gb();this.B={Wd:{}};this.D={Wd:{}};this.Aa=[];this.S={};this.La={};this.ea=!1;this.Rb=g.xI(this.videoData);this.fb=g.uHa(this.videoData,this.G);this.Kb=!!this.videoData.captionTracks.length;this.kc=!!this.videoData.xd;this.Qa="3"===this.Y.controlsType;this.u=this.I=this.J=this.Ia=this.kb=null;this.Va=new T5(this.G,this.Y);this.j=null;this.oa=new g.ZD(this);this.Ya=new g.W({F:"div",N:"ytp-caption-window-container",
X:{id:"ytp-caption-window-container"}});var c=null,d=g.Po("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.Do(d));this.storage=c;var e;this.yb=!(null==(e=a.Td())||!e.HA());this.C=Y3a(this);this.Z=!this.C&&this.Qa&&this.yb&&this.fb;g.M(this,this.Va);this.C?this.Ba=this.xa=null:(this.xa=new g.Wn(this.AL,void 0,this),g.M(this,this.xa),this.Ba=new g.Yn(this.j4,2E3,this),g.M(this,this.Ba));g.M(this,this.oa);this.Y.K("caption_window_container_killswitch")||g.CN(this.player,this.Ya.element,4);
g.M(this,this.Ya);this.C||this.oa.T(a,"resize",this.CL);(this.Gb=!g.Wy()&&!this.G.isFullscreen()&&!this.C&&!this.Z&&!this.Y.K("switch_captions_to_track_tag_when_fullscreen_api_unavailable_killswitch"))&&this.oa.T(a,"resize",this.F1);this.oa.T(a,"onPlaybackAudioChange",this.J0);this.oa.T(a,g.uA("captions"),function(f){b.onCueRangeEnter(f)});
this.oa.T(a,g.vA("captions"),function(f){b.onCueRangeExit(f)});
Z3a(this,$3a(this)||{})},d4a=function(a){if(1===a.Y.kb||1===a.videoData.Rx||"alwayson"===g.gI(a.videoData,"yt:cc"))return!0;
if(a.videoData.captionTracks.length)var b=a.player.getAudioTrack().u;if(2===a.Y.kb){var c;g.qG(a.Y)?c=a4a(a):c=b4a(a,"module-enabled");if(null!=c)return!!c}c=M2a(a.player.getAudioTrack(),N2a(a.Y));var d=g.gI(a.videoData,"yt:cc");if(void 0===c4a(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===c)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===c)return"on"===d}else return"on"===d;return"ON"===b||"on"===g.gI(a.videoData,"yt:cc")},V5=function(a,b){if(a.j&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
a=a.player.getAudioTrack();return!!a.j||"FORCED_ON"===a.u},c4a=function(a){var b=void 0,c=g.tv(g.rv.getInstance(),65);
if(g.qG(a.Y)&&null!=c){if(null!=a4a(a))return!1;b=!c}return b},e4a=function(a){var b;
a.Rb?b=new s5(a.Y,a.videoData,a.player.getAudioTrack(),a.player):a.fb?b=new q5(a.videoData.j,a.player):a.Kb?b=new g.hO(a.Y,a.videoData,a.player.getAudioTrack()):b=new g.kO(a.Y,a.videoData.xd,a.videoData.videoId,g.VBa(a.videoData),a.videoData.Vk);return b},X5=function(a,b){if(a.u){if(a.I&&a.I.C)return a.I.C;
b||(b=a.kc?!1:a.Kb?!1:!0);b=g.eO(a.u.j,b);for(var c=[a.videoData.captionsLanguagePreference,a.Y.captionsLanguagePreference,g.gI(a.videoData,"yt:cc_default_lang")],d=0;d<c.length;d++)for(var e=0;e<b.length;e++)if(g.MG(b[e])===c[d])return b[e];return a.I&&a.I.B?a.I.B:(c=b.find(function(f){return f.isDefault}))?c:b[0]||W5(a)}return null},W5=function(a){return a.I&&a.I.j},Y5=function(a){var b=W5(a);
return!!b&&a.j===b},f4a=function(a){g.eO(a.u.j,!0);
var b=M2a(a.player.getAudioTrack(),N2a(a.Y)),c;"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===b?c=X5(a,a.ea):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===b&&V5(a)?c=W5(a):c4a(a)||a.ea||d4a(a)?c=X5(a,a.ea):V5(a)&&(c=W5(a));if(a.C||a.Z){var d=g.eO(a.u.j,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.ih("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.KG(f));h.setAttribute("srclang",g.MG(f));h.setAttribute("id",f.toString());a.Z||h.setAttribute("src",a.u.Cs(f,"vtt"));f===c&&h.setAttribute("default",
"1");b.push(h)}c=a.G.Td();c.Vx(b);c=c.yf();a.yb&&a.oa.T(c.textTracks,"change",a.o3)}else!a.j&&c&&Z5(a,c),a.player.Pa("onCaptionsTrackListChanged"),a.player.Pa("onApiChange")},g4a=function(a,b){var c=a.G.Td().yf().textTracks;
a=a.j.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},Z5=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.ea=c,a.ea&&(g.qG(a.Y)?$5(a,!!b):a6(a,"module-enabled",!!b)));a.j=b;V5(a)&&(a.j=W5(a));a.load()},i4a=function(a,b){if(b instanceof w5){var c=a.S[b.id];
c&&c.u!==b&&(c.dispose(),delete a.S[b.id],c=null);c||(c=h4a(a,b))&&(a.S[b.id]=c)}else c=b.windowId,a.La[c]||(a.La[c]=[]),a.La[c].push(b)},j4a=function(a,b){a.Y.K("caption_window_container_killswitch")?g.CN(a.player,b,4):a.Ya.element.appendChild(b)},h4a=function(a,b){var c=a.ob.getVideoContentRect(!0).height,d=a.ob.getVideoContentRect(!0).width;
if(!c||!d)return null;var e=a.j?g.MG(a.j):null;e&&g.XYa.test(e)&&(b.params.lh=1);e=a.ob.getPlayerSize();a.Y.K("web_player_caption_stickiness_for_glive_killswitch")||"google-live"!==a.Y.playerStyle||a.B.isDefault||Object.assign(b.params,a.B);switch(null!=b.params.ww?b.params.ww:1<b.j.length?1:0){case 1:return new t5(b,a.B,a.D,d,c,e.width,e.height,a.Y.experiments);case 2:return new u5(b,a.B,a.D,d,c,e.width,e.height,a.Y.experiments);default:return new r5(b,a.B,a.D,d,c,e.width,e.height,a.Y.experiments)}},
Z3a=function(a,b,c){c=void 0===c?!1:c;
var d=b6.Wd;a.B={};Object.assign(a.B,b6);a.B.Wd={};Object.assign(a.B.Wd,d);a.D={Wd:{}};var e=b.backgroundOverride?a.D:a.B,f=b.background||d.background;D5.test(f);e.Wd.background=f;e=b.colorOverride?a.D:a.B;f=b.color||d.color;D5.test(f);e.Wd.color=f;e=b.windowColorOverride?a.D:a.B;f=b.windowColor||b6.windowColor;D5.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.D:a.B;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Wd.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.D:a.B;f=b.fontSizeIncrement;
null==f&&(f=d.fontSizeIncrement);e.Wd.fontSizeIncrement=f;f=b.fontStyleOverride?a.D:a.B;e=b.fontStyle;null==e&&(e=d.bold&&d.italic?3:d.bold?1:d.italic?2:0);f=f.Wd;switch(e){case 1:f.bold=!0;delete f.italic;break;case 2:delete f.bold;f.italic=!0;break;case 3:f.bold=!0;f.italic=!0;break;default:delete f.bold,delete f.italic}e=b.textOpacityOverride?a.D:a.B;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Wd.textOpacity=f;e=b.windowOpacityOverride?a.D:a.B;f=b.windowOpacity;null==f&&(f=b6.windowOpacity);e.windowOpacity=
f;e=b.charEdgeStyleOverride?a.D:a.B;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Wd.charEdgeStyle=f;e=b.fontFamilyOverride?a.D:a.B;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Wd.fontFamily=f;a.loaded&&a.CL();c&&(a.Y.K("web_player_local_storage_for_captions_setting_killswitch")?a6(a,"display-settings",b):g.Pz("yt-player-caption-display-settings",b,2592E3))},l4a=function(a,b,c){b&&!a.J?(b=k3a({lh:0,
lang:"es"}),a.J=[b,new v5(b.start,b.end-b.start,0,b.id,null!=c?c:"Los subt\u00edtulos tendr\u00e1n este aspecto")],a.player.qe(a.J)):!b&&a.J&&(k4a(a,a.J),a.J=null)},k4a=function(a,b){a.player.jh(b);
b=g.r(b);for(var c=b.next();!c.done;c=b.next())g.ac(a.Aa,c.value);g.Xn(a.xa)},b4a=function(a,b){if(!a.storage)return null;
try{var c=a.storage.get(b)}catch(d){a.storage.remove(b)}return c},a6=function(a,b,c){if(a.storage)try{a.storage.set(b,c)}catch(d){}},$5=function(a,b){a.G.isInline()||g.Pz("yt-player-sticky-caption",b,2592E3)},a4a=function(a){if(!a.G.isInline())return g.Qz("yt-player-sticky-caption")},$3a=function(a){return a.Y.K("web_player_local_storage_for_captions_setting_killswitch")?b4a(a,"display-settings"):g.Qz("yt-player-caption-display-settings")},Y3a=function(a){var b,c=!(null==(b=a.G.Td())||!b.GA());
return a.Qa&&c&&!a.fb};
g.CS.prototype.Ny=g.ba(34,function(a){var b=2;this.La.has(a)?b=0:g.JKa(this,a)&&(b=1);return b});
g.uV.prototype.Ny=g.ba(33,function(a){return this.qd.Ny(a)});
g.CS.prototype.QA=g.ba(32,function(a,b,c){this.Ba.set(a,{gs:b,Tx:c})});
g.uV.prototype.QA=g.ba(31,function(a,b,c){this.qd.QA(a,b,c)});
g.yO.prototype.vv=g.ba(29,function(){for(var a=g.bh(document,"track",void 0,this.j),b=0;b<a.length;b++)g.ph(a[b])});
g.mS.prototype.vv=g.ba(28,function(){this.mediaElement.vv()});
g.yO.prototype.HA=g.ba(27,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.mS.prototype.HA=g.ba(26,function(){return this.mediaElement.HA()});
g.yO.prototype.GA=g.ba(25,function(){return!!this.j.textTracks});
g.mS.prototype.GA=g.ba(24,function(){return this.mediaElement.GA()});
g.yO.prototype.Vx=g.ba(23,function(a){for(var b=0;b<a.length;b++)this.j.appendChild(a[b])});
g.mS.prototype.Vx=g.ba(22,function(a){this.mediaElement.Vx(a)});
g.gO.prototype.eK=g.ba(21,function(){return!1});
g.gO.prototype.iq=g.ba(20,function(){});
g.hO.prototype.iq=g.ba(19,function(a,b,c){var d=this;this.isDisposed();b=this.Cs(a,b);this.ep();this.u=g.Cu(b,{format:"RAW",onSuccess:function(e){d.u=null;c(e.responseText,a)},
withCredentials:!0})});
g.kO.prototype.iq=g.ba(18,function(a,b,c){var d=this;this.isDisposed();b=this.Cs(a,b);this.ep();this.u=g.Cu(b,{format:"RAW",onSuccess:function(e){d.u=null;c(e.responseText,a)},
withCredentials:!0})});
g.jV.prototype.Zy=g.ba(8,function(){return this.J});
g.NX.prototype.Zy=g.ba(7,function(){var a;return(null==(a=g.qN(this))?void 0:a.Qv())||null});
g.vN.prototype.Qv=g.ba(6,function(){return this.app.Zy()});
g.nX.prototype.Qv=g.ba(5,function(){var a;return(null==(a=this.Ka)?void 0:a.Zy())||null});
var S2a=/#(.)(.)(.)/,R2a=/^#(?:[0-9a-f]{3}){1,2}$/i,Y2a={aa:"Afar",ab:"Abkhazian",ace:"Achinese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgn:"Western Balochi",bho:"Bhojpuri",
bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksika",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",chg:"Chagatai",chk:"Chuukese",
chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",ckb_Arab:"Central Kurdish (Arabic)",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fulah",ff_Adlm:"Fulah (Adlam)",ff_Latn:"Fulah (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",
goh:"Old High German",gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",
ii:"Sichuan Yi",ik:"Inupiaq",ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",
kj:"Kuanyama",kk:"Kazakh",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Lahnda",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",
lg:"Ganda",li:"Limburgish",lkt:"Lakota",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",
mic:"Mi'kmaq",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",
ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",
pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",
sah:"Sakha",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",
sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",
ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",
ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vi:"Vietnamese",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",
za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};p5.prototype.contains=function(a){a=g.lc(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
p5.prototype.length=function(){return this.segments.length/2};
g.v(V2a,g.K);g.k=V2a.prototype;g.k.ra=function(){g.K.prototype.ra.call(this);this.B&&this.B.cancel()};
g.k.zw=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Bd();var b=this.j;this.j=g.Rb(this.ea.Jm(a).j);b!==this.j&&this.Z&&this.Z()};
g.k.reset=function(){this.C=new p5;this.I=-1;this.B&&(this.B.cancel(),this.B=null)};
g.k.iQ=function(){this.isDisposed();var a;if(a=null!=this.j)a=this.j,a=a.j.mp(a);if(a&&!this.B&&!(this.j&&30<this.j.startTime-this.player.getCurrentTime())){a=this.j;a=a.j.Lx(a);var b;if(null==(b=this.player.getVideoData())?0:b.enableServerStitchedDai){var c=this.player.Qv();if(c){var d=a.j[0].Na;if(b=c.Gm(a.j[0].C,d,a.j[0].j.info.id,3))if(c=c.Ny(d),0===c)b&&(a.B=new g.MB(b));else if(2===c){this.J.start();W2a(this)&&this.seekTo(this.player.getCurrentTime());return}}}a.j[0].duration?(this.C.contains(a.j[0].Na)||
X2a(this,a),this.j=g.Rb(a.j)):!this.Y.K("force_caption_seek_for_live_killswitch")&&W2a(this)&&this.seekTo(this.player.getCurrentTime())}this.J.start()};
g.v(q5,g.gO);g.k=q5.prototype;g.k.iq=function(a,b,c){var d=this;this.ep();b=$2a(this,a.getId());b||(b=a.languageCode,b=this.u.isManifestless?a3a(this,b,"386"):a3a(this,b));if(b){var e=1E3*(b.index.getStartTimeInPeriod(b.index.getFirstSegmentNumber())-b.index.getStartTime(b.index.getFirstSegmentNumber())),f=new g.iO(this.Y);this.B=new V2a(f,this.G,b,function(h,l){c(h,a,l,e)},this.I||g.ID(b.info),function(){d.B&&d.B.reset();
d.D=!0})}};
g.k.eK=function(){var a=this.D;this.D=!1;return a};
g.k.ow=function(a){var b=this.I?[new g.JG({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.JG({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.u.isManifestless?Z2a(this,"386"):Z2a(this);b=g.r(b);for(var c=b.next();!c.done;c=b.next())g.fO(this.j,c.value);a()};
g.k.ep=function(){this.B&&(this.B.dispose(),this.B=null)};
g.k.Cs=function(){return""};
var D5=/^#(?:[0-9a-f]{3}){1,2}$/i;var c3a=["left","right","center","justify"];g.v(r5,g.W);g.k=r5.prototype;g.k.wU=function(a,b){var c=g.Gl(this.element,this.element.parentElement);this.kb=a-c.x;this.ob=b-c.y;g.go(this.element,"ytp-dragging")};
g.k.vU=function(a,b){var c=g.Il(this.element);a=a-this.kb-.02*this.playerWidth;var d=b-this.ob-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.Bg(e,0,2));var f=(d+c.height/2)/this.Ya*3;f=Math.floor(g.Bg(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.Bg(a,0,1);c=(d+f/2*c.height)/this.Ya;c=100*g.Bg(c,0,1);this.u.params.Vj=b;this.u.params.Gl=c;this.u.params.Pi=a;this.u.params.isDefault=!1;this.j.Vj=b;this.j.Gl=c;this.j.Pi=a;this.j.isDefault=!1;this.ea.Vj=b;this.ea.Gl=c;
this.ea.Pi=a;this.ea.isDefault=!1;this.hS()};
g.k.uU=function(){g.io(this.element,"ytp-dragging")};
g.k.hS=function(){this.Uw(this.D)};
g.k.getType=function(){return this.type};
g.k.Uw=function(a){var b=Math.min(this.YO(),this.maxWidth),c=this.XO(),d="";3===this.u.params.lh&&(d="rotate(180deg)");g.xl(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.zG(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.j.Pi+2;d=this.j.Vj;switch(d){case 0:case 3:case 6:(b=this.j.Wd.fontSizeIncrement)&&0<b&&2!==this.j.lh&&3!==
this.j.lh&&(e=Math.max(e/(1+2*b),2));a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.C.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.j.Gl+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.xl(this.element,
a)};
g.k.zG=function(a){var b;for(b=0;b<a.length&&a[b]===this.D[b];b++);if(this.Ba||this.D.length>b)b=0,this.Ba=!1,this.D=[],this.I=this.La=this.Ia=null,g.nh(this.C);for(;b<a.length;b++)g3a(this,a[b])};
g.k.YO=function(){return 0};
g.k.XO=function(){return 0};
g.k.toString=function(){return g.W.prototype.toString.call(this)};g.v(s5,g.gO);s5.prototype.iq=function(a,b,c){Q2a(this.videoData.videoId,a.vssId,c)};
s5.prototype.ow=function(a){if(this.audioTrack)for(var b=g.r(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.fO(this.j,c.value);a()};g.v(t5,r5);t5.prototype.zG=function(a){var b=this.u.j;r5.prototype.zG.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.j===e)var d=f;else{d={};Object.assign(d,c.j);Object.assign(d,m4a);var e=c.j;var f=d}g3a(this,c,d)}};
var m4a={NZ:!0};g.v(u5,r5);g.k=u5.prototype;g.k.hS=function(){g.$n(this.Va)};
g.k.D2=function(){g.io(this.element,"ytp-rollup-mode");this.Uw(this.Kb,!0)};
g.k.XO=function(){return this.B?this.Z:this.S};
g.k.YO=function(){return this.B?this.S:this.Z};
g.k.Uw=function(a,b){this.Kb=a;if(this.u.params.So){for(var c=0,d=0;d<this.D.length&&c<a.length;d++)this.D[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.D.concat(a.slice(c)));this.yb=this.Z;this.S=this.Z=0;r5.prototype.Uw.call(this,a);j3a(this,b)}r5.prototype.Uw.call(this,a)};g.v(v5,g.sA);v5.prototype.toString=function(){return g.sA.prototype.toString.call(this)};g.v(w5,g.sA);w5.prototype.toString=function(){return g.sA.prototype.toString.call(this)};
var x5=0;g.v(y5,g.K);y5.prototype.u=function(){return[]};
y5.prototype.reset=function(){};g.v(z5,y5);z5.prototype.reset=function(){this.J={};this.B=this.j=null;this.I=!0};
z5.prototype.u=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.r(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.r(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,h={},l=a.getAttribute("p");l&&Object.assign(h,this.pens[l]);l=B5(a,"b");
null!=l&&(h.bold=l);l=B5(a,"i");null!=l&&(h.italic=l);l=B5(a,"u");null!=l&&(h.underline=l);l=C5(a,"et");null!=l&&(h.charEdgeStyle=l);l=C5(a,"of");null!=l&&(h.offset=l);l=E5(a,"bc");null!=l&&(h.background=l);l=E5(a,"ec");null!=l&&(h.PG=l);l=E5(a,"fc");null!=l&&(h.color=l);l=C5(a,"fs");null!=l&&0!==l&&(h.fontFamily=l);l=A5(a,"sz");void 0!==l&&(h.fontSizeIncrement=l/100-1);l=A5(a,"bo");void 0!==l&&(h.backgroundOpacity=l/255);l=A5(a,"fo");void 0!==l&&(h.textOpacity=l/255);l=C5(a,"rb");null!=l&&10!==l&&
0!==l&&(h.gf=10<l?l-1:l);a=C5(a,"hg");null!=a&&(h.FP=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.Z[c]=n3a(this,a);break;case "wp":c=a.getAttribute("id"),this.S[c]=o3a(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.r(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.j=p3a(this,a,b,!1);(a=this.J[this.j.id])&&a.end>this.j.start&&(a.end=this.j.start);this.J[this.j.id]=this.j;d.push(this.j);break;case "p":l=b;c=[];f=a.getAttribute("w")||this.D;
h=!!B5(a,"a");l=(A5(a,"t")||0)+l;var m=A5(a,"d")||5E3;h||(!this.I&&this.B&&this.B.windowId===f&&this.B.end>l&&(this.B.end=l),this.B&&"\n"===this.B.text&&(this.B.text=""));var n=h?6:5,p=a.getAttribute("p");p=p?this.pens[p]:null;var q=Array.from(a.childNodes);q.length&&(this.I=null!=a.getAttribute("d"));for(var u=0;u<q.length;u++){var w=q[u],y=void 0;0<u&&(h=!0);var A=void 0;1===w.nodeType&&(A=w);if(A&&"s"===A.tagName){if((w=(w=A.getAttribute("p"))?this.pens[w]:null)&&w.gf&&(1===w.gf?(w=q.slice(u,u+
4),4===w.length&&(y=m3a(l,m,f,h,n,w,this.pens),u+=3)):y=m3a(l,m,f,h,n,[A],this.pens)),!y){var B=A;y=l;A=m;w=f;var D=h,G=n,F=B.textContent?B.textContent:"",I=B.getAttribute("p");I=I?this.pens[I]:null;B=A5(B,"t")||0;y=new v5(y+B,A-B,G,w,F,D,I)}}else y=new v5(l,m,n,f,w.textContent||"",h,p);c.push(y);this.B=y}if(0<c.length)for(c[0].windowId===this.D&&(this.j=p3a(this,a,b,!0),d.push(this.j)),a=g.r(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.j.id,this.j.j.push(c),d.push(c)}b=d}else b=[];
return b};var n4a=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.v(F5,y5);F5.prototype.reset=function(){this.B.clear()};
F5.prototype.u=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.r(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.j.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.italic=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;null!=h&&(f.offset=h);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;null!=h&&(f.charEdgeStyle=h);void 0!==e.ecEdgeColor&&(f.PG=G5(e.ecEdgeColor));h=e.fsFontStyle;null!=h&&0!==h&&(f.fontFamily=
h);void 0!==e.fcForeColor&&(f.color=G5(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=G5(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&10!==h&&(f.gf=10<h?h-1:h,f.Fl=n4a.get(f.gf));e.hgHorizGroup&&(f.FP=e.hgHorizGroup);this.j.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.r(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.D.get(h)):Object.assign(f,
this.I),void 0!==e.mhModeHint&&(f.ww=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.lh=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.hL=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=G5(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.D.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.r(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.C.get(h)),void 0!==e.ahHorPos&&
(f.Pi=e.ahHorPos),void 0!==e.apPoint&&(f.Vj=e.apPoint),void 0!==e.avVerPos&&(f.Gl=e.avVerPos),void 0!==e.ccCols&&(f.Bp=e.ccCols),void 0!==e.rcRows&&(f.So=e.rcRows),this.C.set(a++,f);if(c.events){a=[];c=g.r(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;d=(l.tStartMs||0)+b;e=l.dDurationMs||0;if(l.id)f=String(l.id),d=q3a(this,l,d,e,f),a.push(d),this.B.set(f,d);else{l.wWinId?f=l.wWinId.toString():(f="_"+x5++,h=q3a(this,l,d,e,f),a.push(h),this.B.set(f,h));0===e&&(e=5E3);h=this.B.get(f);var m=
!!l.aAppend,n=m?6:5,p=l.segs,q=null;l.pPenId&&(q=this.j.get(l.pPenId));for(l=0;l<p.length;l++){var u=p[l],w=u.utf8;if(w){var y=u.tOffsetMs||0,A=null;u.pPenId&&(A=this.j.get(u.pPenId));if(2===(null!=h.params.ww?h.params.ww:1<h.j.length?1:0)&&m&&"\n"===w)continue;if(u=A&&1===A.gf)if(u=l,u+3>=p.length||!p[u+1].pPenId||!p[u+2].pPenId||!p[u+3].pPenId)u=!1;else{var B=p[u+1].pPenId;(B=this.j.get(B))&&B.gf&&2===B.gf?(B=p[u+2].pPenId,B=this.j.get(B),!B||!B.gf||3>B.gf?u=!1:(B=p[u+3].pPenId,u=(B=this.j.get(B))&&
B.gf&&2===B.gf?!0:!1)):u=!1}if(u){y=p[l+1].utf8;u=p[l+3].utf8;B=p[l+2].utf8;var D=this.j.get(p[l+2].pPenId);w=l3a(w,y,B,u,D);m=new v5(d,e,n,f,w,m,A);l+=3}else m=new v5(d+y,e-y,n,h.id,w,m,A||q);m&&(a.push(m),h.j.push(m))}m=!0}}}b=a}else b=[];return b};s3a.prototype.clear=function(){this.B=this.time=this.mode=0;this.j=[];this.reset()};
s3a.prototype.reset=function(){this.mode=0;this.C.reset(0);this.D.reset(1)};
var t3a=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];H5.prototype.set=function(a){this.type=a};
H5.prototype.get=function(){return this.type};
I5.prototype.clear=function(){this.state=0};
I5.prototype.update=function(){this.state=2===this.state?1:0};
I5.prototype.isValid=function(){return 0!==this.state};
I5.prototype.matches=function(a,b){return this.isValid()&&a===this.Lr&&b===this.yp};
y3a.prototype.reset=function(){this.timestamp=this.j=0};
J5.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.B[b][c].timestamp=a};
J5.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.B[b][c];a=0===d.j?a+"_":a+String.fromCharCode(d.j)}a+="\n"}return a};
J5.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.B[b][c].reset();this.C=a;this.j=0;this.u=this.row=1};
var z3a=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],A3a=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],B3a=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],C3a=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];G3a.prototype.reset=function(a,b){this.D=b;this.style.set(2);this.u=this.I;this.C=this.J;this.j=this.u;var c=(a<<2)+(b<<1);this.I.reset(c);this.J.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
r3a.prototype.reset=function(a){this.D=a;this.u.clear();this.C=this.B;this.B.reset(a,0);this.I.reset(a,1)};K3a.prototype.C=function(){};g.v(O5,K3a);O5.prototype.C=function(a,b,c,d,e){if(c<d){var f="_"+x5++;c=c/1E3-this.I;d=d/1E3-this.I;a=new w5(c,d-c,5,f,{textAlign:0,Vj:0,Pi:2.5*b,Gl:5.33*a});e=new v5(c,d-c,5,f,e);this.u.push(a);this.u.push(e)}};
g.v(R5,y5);R5.prototype.u=function(a){a=new O5(a,a.byteLength,this.B);if(L3a(a)){for(;a.byteOffset<a.j.byteLength;)for(0===a.version?a.B=Q5(a)*(1E3/45):1===a.version&&(a.B=4294967296*Q5(a)+Q5(a)),a.D=P5(a);0<a.D;a.D--){var b=P5(a),c=P5(a),d=P5(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.j,b.j.push({time:a.B,type:this.track,dO:c,eO:d,order:b.j.length}))}x3a(this.j,a);return a.u}return[]};
R5.prototype.reset=function(){this.j.clear()};g.v(S5,y5);
S5.prototype.u=function(a,b){var c=[];a=a.split(o4a);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!p4a.test(e)){var h=q4a.exec(e);if(h&&4<=h.length){var l=O3a(h[1]),m=O3a(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var q="";var u=null,w="";n=g.r(n);for(var y=n.next();!y.done;y=n.next())if(y=y.value.split(":"),2===y.length){var A=y[1];switch(y[0]){case "line":y=A.split(",");y[0].endsWith("%")&&(p=y[0],h.Gl=Number.parseInt(p,10),2===y.length&&(q=y[1].trim()));break;case "position":y=
A.split(",");u=y[0];h.Pi=Number.parseInt(u,10);2===y.length&&(w=y[1].trim());break;case "align":switch(A){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||q||(q="end");if(!u)switch(h.textAlign){case 0:h.Pi=0;break;case 1:h.Pi=100;break;case 2:h.Pi=50}if(null!=h.textAlign){p=0;switch(q){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(w){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}q=0>p||8<p?7:p;h.Vj=q}e=e.substring(q4a.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");w=h;h=e;e={};if(0>h.indexOf("<")&&0>h.indexOf("&"))f=P3a(l,m,5,w),m=new v5(l,m,5,f.id,h,!1,g.Bf(e)?void 0:e),c.push(f),c.push(m),f.j.push(m);else for(q=h.split(r4a),1===q.length?(h=5,w=P3a(l,m,h,w)):(p=h=6,w=Object.assign({Bp:32},w),w=new w5(l,m,p,"_"+x5++,w)),c.push(w),p=l,u=0;u<q.length;u++)n=q[u],0===u%2?(y=g.GXa("<html>"+n+"</html>"),y.getElementsByTagName("parsererror").length?
(A=y.createElement("span"),A.appendChild(y.createTextNode(n))):A=y.firstChild,N3a(this,p,m-(p-l),h,w,0<u,A,e,c)):p=O3a(n)+f}q4a.lastIndex=0}}return c};
var p4a=/^NOTE/,o4a=/(?:\r\n|\r|\n){2,}/,q4a=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),r4a=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.oS.XC(S5,{u:"wvppt"});g.v(T5,g.K);T5.prototype.clear=function(){this.parser&&this.parser.dispose();this.parser=null};
T5.prototype.reset=function(){this.parser&&this.parser.reset()};
T5.prototype.ra=function(){g.K.prototype.ra.call(this);this.clear()};var b6={windowColor:"#080808",windowOpacity:0,textAlign:2,Vj:7,Pi:50,Gl:100,isDefault:!0,Wd:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.v(U5,g.dO);g.k=U5.prototype;g.k.ra=function(){if(this.C||this.Z){var a=this.G.Td();a&&!a.isDisposed()&&a.vv()}else l4a(this,!1);g.dO.prototype.ra.call(this)};
g.k.Ot=function(){if(this.Qa)return this.C||this.Z;var a=M2a(this.player.getAudioTrack(),N2a(this.Y));return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?V5(this):c4a(this)||V5(this)?!0:d4a(this)};
g.k.load=function(){var a=this;g.dO.prototype.load.call(this);var b=!this.Y.K("web_player_captions_track_list_changed_killswitch");this.I=this.player.getAudioTrack();this.u?(this.j&&(this.Va.clear(),this.C?g4a(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.iq(this.j,"json3",function(c,d,e,f){if(c){a.u.eK()&&(a.Aa=[],a.G.Ff("captions"),g.Xn(a.xa),a.Va.reset());c=V3a(a.Va,c,d,e,f);a.player.qe(c,void 0,a.fb);if(!(!a.ea||a.Z||Y5(a)||g.dG(a.Y)||g.VF(a.Y))){g.ao(a.Ba);c=k3a({Vj:0,Pi:5,Gl:5,
So:2,textAlign:0,lh:0,lang:"es"});a.Ia=[c];e=["Haz clic en "," para ir a la configuraci\u00f3n"];a.kb||(f=new g.WK(g.mL()),g.M(a,f),a.kb=f.element);f=c.end-c.start;var h=g.KG(a.j);h&&a.Ia.push(new v5(c.start,f,0,c.id,h));a.Ia.push(new v5(c.start,f,0,c.id,e[0]),new v5(c.start,f,0,c.id,a.kb,!0),new v5(c.start,f,0,c.id,e[1],!0));a.player.qe(a.Ia);g.Zn(a.Ba)}!a.ea||a.Z||Y5(a)||(g.qG(a.Y)?$5(a,!0):a6(a,"module-enabled",!0),a.I&&(a.I.C=a.j),a.player.Yt());var l;null==(l=a.G.Jc())||l.va("cc",{kind:d.kind});
a.ea=!1}}),!b||this.C||this.Z||Y5(this)||this.player.Pa("captionschanged",g.LG(this.j))),b||(this.j&&!Y5(this)?this.player.Pa("captionschanged",g.LG(this.j)):this.player.Pa("onCaptionsTrackListChanged"))):(this.u=e4a(this),g.M(this,this.u),this.u.ow(function(){f4a(a)}))};
g.k.unload=function(){this.C&&this.j?g4a(this,!1):(this.Ba&&g.ao(this.Ba),this.player.Ff("captions"),this.Aa=[],this.u&&this.u.ep(),this.Va.clear(),this.J&&this.player.qe(this.J),this.CL());g.dO.prototype.unload.call(this);this.player.Yt();this.player.Pa("captionschanged",{})};
g.k.create=function(){this.Ot()&&this.load()};
g.k.o3=function(){for(var a=this.G.Td().yf().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;for(var d=g.eO(this.u.j,!0),e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.j:null)!==b&&Z5(this,b,!0)};
g.k.a6=function(){!this.j&&this.C||this.unload()};
g.k.onCueRangeEnter=function(a){this.Aa.push(a);g.Xn(this.xa)};
g.k.onCueRangeExit=function(a){g.ac(this.Aa,a);this.u instanceof q5&&this.u.I&&this.player.jh([a]);g.Xn(this.xa)};
g.k.getCaptionWindowContainerId=function(){return this.Ya.element.id};
g.k.j4=function(){k4a(this,this.Ia);this.Ia=null};
g.k.AL=function(){var a=this;if(!this.Gb||!this.C){this.xa.stop();g.Dca(this.La);this.Aa.sort(g.tA);var b=this.Aa;if(this.J){var c=g.sm(b,function(f){return-1===this.J.indexOf(f)},this);
c.length&&(b=c)}b=g.r(b);for(c=b.next();!c.done;c=b.next())i4a(this,c.value);b={};c=g.r(Object.entries(this.S));for(var d=c.next();!d.done;b={Vq:b.Vq,Qk:b.Qk},d=c.next()){var e=g.r(d.value);d=e.next().value;e=e.next().value;b.Vq=d;b.Qk=e;this.La[b.Vq]?(b.Qk.element.parentNode||(b.Qk instanceof u5||b.Qk instanceof t5||g.rf(this.S,function(f){return function(h,l){l!==f.Vq&&h.u.params.Vj===f.Qk.u.params.Vj&&h.u.params.Pi===f.Qk.u.params.Pi&&h.u.params.Gl===f.Qk.u.params.Gl&&(h.dispose(),delete a.S[l]);
return l===f.Vq}}(b),this),j4a(this,b.Qk.element)),b.Qk.Uw(this.La[b.Vq])):(b.Qk.dispose(),delete this.S[b.Vq])}}};
g.k.q4=function(){Z3a(this,{},!0);this.Y.K("web_player_disable_publish_captions_settings_changed_on_reset")||this.player.Pa("captionssettingschanged")};
g.k.iZ=function(){var a=b6.Wd;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.italic?3:a.bold?1:a.italic?2:0,textOpacity:a.textOpacity,windowColor:b6.windowColor,windowOpacity:b6.windowOpacity};var b=$3a(this)||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.rT=function(a,b){var c={};Object.assign(c,$3a(this));Object.assign(c,a);Z3a(this,c,b);this.player.Pa("captionssettingschanged")};
g.k.CL=function(){!this.C&&this.loaded&&(g.of(this.S,function(a,b){a.dispose();delete this.S[b]},this),this.AL())};
g.k.Cg=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Bg(b,-2,4);this.rT({fontSizeIncrement:c});return c;case "reload":b&&!this.C&&Z5(this,this.j,!0);break;case "stickyLoading":void 0!==b&&this.Y.C&&(g.qG(this.Y)?$5(this,!!b):a6(this,"module-enabled",!!b));break;case "track":if(!this.u)return{};if(b){if(this.C)break;if(!g.Na(b))break;if(g.Bf(b)){Z5(this,null,!0);break}a=g.eO(this.u.j,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&e.languageName!==
b.languageName||(c=b.translationLanguage?O2a(e,b.translationLanguage):e)}!c||c===this.j&&this.loaded||(b=g.qya(),a=g.MG(c),b.length&&a===b[b.length-1]||(b.push(a),g.Pz("yt-player-caption-language-preferences",b)),Z5(this,c,!0))}else return this.loaded&&this.j&&!Y5(this)?g.LG(this.j):{};return"";case "tracklist":return this.u?g.Ok(g.eO(this.u.j,!(!b||!b.includeAsr)),function(f){return g.LG(f)}):[];
case "translationLanguages":return this.u?this.u.C.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.C||void 0===b||l4a(this,!!b);break;case "sampleSubtitlesCustomized":this.C||l4a(this,!!b,b)}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.Y.C&&a.push("stickyLoading");return a};
g.k.cI=function(){var a=this.j;if(a){var b=a.vssId;a.translationLanguage&&b&&!this.Y.K("auto_translation_logging_killswitch")&&(b="t"+b+"."+g.MG(a));return{cc:b}}return{}};
g.k.G5=function(){this.loaded&&this.j&&!Y5(this)?(g.qG(this.Y)?$5(this,!1):a6(this,"module-enabled",!1),this.unload(),V5(this,!0)&&Z5(this,W5(this),!1)):this.VS()};
g.k.VS=function(){this.loaded&&this.j&&!Y5(this)||Z5(this,Y5(this)||!this.j?X5(this,!0):this.j,!0)};
g.k.J0=function(){var a=Y5(this);V5(this,a)?Z5(this,this.player.getAudioTrack().j,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.Ot()&&(a?Z5(this,X5(this),!1):this.load()))};
g.k.F1=function(){var a=this.G.Td();a&&!a.isDisposed()&&a.vv();this.G.isFullscreen()?(this.C=this.Qa=!0,this.loaded&&f4a(this)):(this.Qa="3"===this.Y.controlsType,this.C=Y3a(this));Z5(this,this.j)};
g.oS.XC(U5,{AL:"smucd"});g.cO("captions",U5);})(_yt_player);
