(function(g){var window=this;'use strict';var G4a=function(a,b){a.Pa("onAutonavCoundownStarted",b)},l6=function(a,b,c){g.ko(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.Nf(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.VG&&(b.lengthText?(e=b.lengthText||null,f=b.Ts||null):b.lengthSeconds&&(e=g.YL(b.lengthSeconds),f=g.YL(b.lengthSeconds,!0)));var h=!!d;d=h&&"RD"===g.TG(d).type;var l=b instanceof g.VG?b.isLivePlayback:null,m=b instanceof g.VG?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,u=[],w=[];n&&u.push(n);p&&(u.push(p),w.push(p));q&&w.push(q);c={title:b.title,author:n,author_and_views:u.join(" \u2022 "),aria_label:b.ariaLabel||
g.IJ("Ver $TITLE",{TITLE:b.title}),duration:e,timestamp:f,url:b.Nm(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:w.join(" \u2022 "),autoplayAlternativeHeader:b.xp};b instanceof g.UG&&(c.playlist_length=b.playlistLength);a.update(c)},m6=function(a){var b=a.V(),c=b.u;
g.W.call(this,{F:"a",N:"ytp-autonav-suggestion-card",X:{href:"{{url}}",target:c?b.J:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},W:[{F:"div",Ga:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],X:{style:"{{background}}"},W:[{F:"div",X:{"aria-label":"{{timestamp}}"},Ga:["ytp-autonav-timestamp"],qa:"{{duration}}"},{F:"div",Ga:["ytp-autonav-live-stamp"],qa:"En directo"},
{F:"div",Ga:["ytp-autonav-upcoming-stamp"],qa:"Pr\u00f3ximamente"},{F:"div",N:"ytp-autonav-list-overlay",W:[{F:"div",N:"ytp-autonav-mix-text",qa:"Mix"},{F:"div",N:"ytp-autonav-mix-icon"}]}]},{F:"div",Ga:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],qa:"{{title}}"},{F:"div",Ga:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],qa:"{{author}}"},{F:"div",Ga:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],qa:"{{views_and_publish_time}}"}]});this.G=
a;this.suggestion=null;this.j=c;this.Ra("click",this.onClick);this.Ra("keypress",this.onKeyPress)},n6=function(a,b){b=void 0===b?!1:b;
g.W.call(this,{F:"div",N:"ytp-autonav-endscreen-countdown-overlay"});var c=this;this.I=b;this.D=void 0;this.u=0;this.container=new g.W({F:"div",N:"ytp-autonav-endscreen-countdown-container"});g.M(this,this.container);this.container.Ca(this.element);b=a.V();var d=b.u;this.G=a;this.suggestion=null;this.onVideoDataChange("newdata",this.G.getVideoData());this.T(a,"videodatachange",this.onVideoDataChange);var e=["ytp-autonav-endscreen-upnext-thumbnail"];b.K("web_rounded_thumbnails")&&e.push("rounded-thumbnail");
this.j=new g.W({F:"div",N:"ytp-autonav-endscreen-upnext-container",X:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},W:[{F:"div",N:"ytp-autonav-endscreen-upnext-header"},{F:"div",N:"ytp-autonav-endscreen-upnext-alternative-header",qa:"{{autoplayAlternativeHeader}}"},{F:"a",N:"ytp-autonav-endscreen-link-container",X:{href:"{{url}}",target:d?b.J:""},W:[{F:"div",Ga:e,X:{style:"{{background}}"},W:[{F:"div",
X:{"aria-label":"{{timestamp}}"},Ga:["ytp-autonav-timestamp"],qa:"{{duration}}"},{F:"div",Ga:["ytp-autonav-live-stamp"],qa:"En directo"},{F:"div",Ga:["ytp-autonav-upcoming-stamp"],qa:"Pr\u00f3ximamente"}]},{F:"div",N:"ytp-autonav-endscreen-video-info",W:[{F:"div",N:"ytp-autonav-endscreen-premium-badge"},{F:"div",N:"ytp-autonav-endscreen-upnext-title",qa:"{{title}}"},{F:"div",N:"ytp-autonav-endscreen-upnext-author",qa:"{{author}}"},{F:"div",N:"ytp-autonav-view-and-date",qa:"{{views_and_publish_time}}"},
{F:"div",N:"ytp-autonav-author-and-view",qa:"{{author_and_views}}"}]}]}]});g.M(this,this.j);this.j.Ca(this.container.element);d||this.T(this.j.Da("ytp-autonav-endscreen-link-container"),"click",this.dM);this.G.vb(this.container.element,this,115127);this.G.vb(this.j.Da("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.W({F:"div",N:"ytp-autonav-overlay"});g.M(this,this.overlay);this.overlay.Ca(this.container.element);this.B=new g.W({F:"div",N:"ytp-autonav-endscreen-button-container"});
g.M(this,this.B);this.B.Ca(this.container.element);this.cancelButton=new g.W({F:"button",Ga:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.K("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{"aria-label":"Cancelar reproducci\u00f3n autom\u00e1tica"},qa:"Cancelar"});g.M(this,this.cancelButton);this.cancelButton.Ca(this.B.element);this.cancelButton.Ra("click",this.CU,this);this.G.vb(this.cancelButton.element,this,115129);this.playButton=
new g.W({F:"a",Ga:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",b.K("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{href:"{{url}}",role:"button","aria-label":"Reproducir siguiente v\u00eddeo"},qa:"Ver ahora"});g.M(this,this.playButton);this.playButton.Ca(this.B.element);this.playButton.Ra("click",this.dM,this);this.G.vb(this.playButton.element,this,115130);this.C=new g.Yn(function(){H4a(c)},500);
g.M(this,this.C);this.cM();this.T(a,"autonavvisibility",this.cM);this.G.K("web_autonav_color_transition")&&(this.T(a,"autonavchange",this.BU),this.T(a,"onAutonavCoundownStarted",this.K0))},o6=function(a){var b=a.G.dk(!0,a.G.isFullscreen());
g.ko(a.container.element,"ytp-autonav-endscreen-small-mode",a.Ig(b));g.ko(a.container.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.AE);g.ko(a.G.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.G.bf());g.ko(a.G.getRootNode(),"countdown-running",a.sj());g.ko(a.container.element,"ytp-player-content",a.G.bf());g.xl(a.overlay.element,{width:b.width+"px"});if(!a.sj()){a.G.bf()?I4a(a,Math.round(J4a(a)/1E3)):I4a(a);b=!!a.suggestion&&!!a.suggestion.xp;var c=a.G.bf()||!b;
g.ko(a.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!c&&b);g.ko(a.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.ZK(a.B,a.G.bf());g.ko(a.element,"ytp-enable-w2w-color-transitions",K4a(a))}},H4a=function(a){var b=J4a(a),c=Math,d=c.min;
var e=a.u?Date.now()-a.u:0;c=d.call(c,e,b);I4a(a,Math.ceil((b-c)/1E3));500>=b-c&&a.sj()?a.select(!0):a.sj()&&a.C.start()},J4a=function(a){if(a.G.isFullscreen()){var b;
a=null==(b=a.G.getVideoData())?void 0:b.lK;return-1===a||void 0===a?8E3:a}return 0<=a.G.Np()?a.G.Np():g.UE(a.G.V().experiments,"autoplay_time")||1E4},K4a=function(a){var b;
return!(null==(b=a.G.getVideoData())||!b.watchToWatchTransitionRenderer)},I4a=function(a,b){b=void 0===b?-1:b;
a=a.j.Da("ytp-autonav-endscreen-upnext-header");g.nh(a);if(0<=b){b=String(b);var c="A continuaci\u00f3n en $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="A continuaci\u00f3n en $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.mh("A continuaci\u00f3n en $SECONDS".slice(0,d)));var e=g.ih("span");g.eo(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.sh(e,b);a.appendChild(e);a.appendChild(g.mh("A continuaci\u00f3n en $SECONDS".slice(d+c.length)));return}}g.sh(a,"Siguiente")},p6=function(a,b){g.W.call(this,
{F:"div",
Ga:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},q6=function(a){g.W.call(this,{F:"div",
Ga:["ytp-upnext","ytp-player-content"],X:{"aria-label":"{{aria_label}}"},W:[{F:"div",N:"ytp-cued-thumbnail-overlay-image",X:{style:"{{background}}"}},{F:"span",N:"ytp-upnext-top",W:[{F:"span",N:"ytp-upnext-header",qa:"Siguiente"},{F:"span",N:"ytp-upnext-title",qa:"{{title}}"},{F:"span",N:"ytp-upnext-author",qa:"{{author}}"}]},{F:"a",N:"ytp-upnext-autoplay-icon",X:{role:"button",href:"{{url}}","aria-label":"Reproducir siguiente v\u00eddeo"},W:[{F:"svg",X:{height:"100%",version:"1.1",viewBox:"0 0 72 72",
width:"100%"},W:[{F:"circle",N:"ytp-svg-autoplay-circle",X:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{F:"circle",N:"ytp-svg-autoplay-ring",X:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{F:"path",N:"ytp-svg-fill",X:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{F:"span",N:"ytp-upnext-bottom",W:[{F:"span",N:"ytp-upnext-cancel"},{F:"span",N:"ytp-upnext-paused",
qa:"La reproducci\u00f3n autom\u00e1tica est\u00e1 en pausa"}]}]});this.api=a;this.cancelButton=null;this.D=this.Da("ytp-svg-autoplay-ring");this.B=this.notification=this.j=this.suggestion=null;this.C=new g.Yn(this.UB,5E3,this);this.u=0;var b=this.Da("ytp-upnext-cancel");this.cancelButton=new g.W({F:"button",Ga:["ytp-upnext-cancel-button","ytp-button"],X:{tabindex:"0","aria-label":"Cancelar reproducci\u00f3n autom\u00e1tica"},qa:"Cancelar"});g.M(this,this.cancelButton);this.cancelButton.Ra("click",
this.DU,this);this.cancelButton.Ca(b);this.cancelButton&&this.api.vb(this.cancelButton.element,this,115129);g.M(this,this.C);this.api.vb(this.element,this,18788);b=this.Da("ytp-upnext-autoplay-icon");this.T(b,"click",this.EU);this.api.vb(b,this,115130);this.eM();this.T(a,"autonavvisibility",this.eM);this.T(a,"mdxnowautoplaying",this.H1);this.T(a,"mdxautoplaycanceled",this.I1);g.ko(this.element,"ytp-upnext-mobile",this.api.V().isMobile)},L4a=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=null==(c=a.api.getVideoData())?void 0:c.lK;return-1===a||void 0===a?8E3:a}return 0<=a.api.Np()?a.api.Np():g.UE(a.api.V().experiments,"autoplay_time")||1E4},M4a=function(a,b){b=L4a(a,b);
var c=Math,d=c.min;var e=(0,g.T)()-a.u;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.D.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.sj()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.sj()&&a.j.start()},r6=function(a){p6.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.W({F:"div",N:"ytp-suggestion-panel",W:[{F:"div",Ga:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],qa:"M\u00e1s v\u00eddeos"}]});this.J=new g.W({F:"div",N:"ytp-suggestions-container"});this.videos=[];this.B=null;this.D=this.I=!1;this.u=new n6(this.player);g.M(this,this.u);this.u.Ca(this.element);a.getVideoData().Me?this.j=this.u:(this.j=new q6(a),g.CN(this.player,this.j.element,4),g.M(this,this.j));this.overlay=new g.W({F:"div",
N:"ytp-autonav-overlay-cancelled-state"});g.M(this,this.overlay);this.overlay.Ca(this.element);this.C=new g.ZD(this);g.M(this,this.C);g.M(this,this.table);this.table.Ca(this.element);this.table.show();g.M(this,this.J);this.J.Ca(this.table.element);this.hide()},s6=function(a){var b=a.bf();
b!==a.D&&(a.D=b,a.player.ma("autonavvisibility"),a.D?(a.u!==a.j&&a.u.hide(),a.table.hide()):(a.u!==a.j&&a.u.show(),a.table.show()))},N4a=function(a){p6.call(this,a,"subscribecard-endscreen");
this.j=new g.W({F:"div",N:"ytp-subscribe-card",W:[{F:"img",N:"ytp-author-image",X:{src:"{{profilePicture}}"}},{F:"div",N:"ytp-subscribe-card-right",W:[{F:"div",N:"ytp-author-name",qa:"{{author}}"},{F:"div",N:"html5-subscribe-button-container"}]}]});g.M(this,this.j);this.j.Ca(this.element);var b=a.getVideoData();this.subscribeButton=new g.hP("Suscribirme",null,"Anular suscripci\u00f3n",null,!0,!1,b.Jk,b.subscribed,"trailer-endscreen",null,null,a);g.M(this,this.subscribeButton);this.subscribeButton.Ca(this.j.Da("html5-subscribe-button-container"));
this.T(a,"videodatachange",this.Ja);this.Ja();this.hide()},t6=function(a){var b=a.V(),c=g.cE||g.LF?{style:"will-change: opacity"}:void 0,d=b.u,e=["ytp-videowall-still"];
b.isMobile&&e.push("ytp-videowall-show-text");g.W.call(this,{F:"a",Ga:e,X:{href:"{{url}}",target:d?b.J:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},W:[{F:"div",N:"ytp-videowall-still-image",X:{style:"{{background}}"}},{F:"span",N:"ytp-videowall-still-info",W:[{F:"span",N:"ytp-videowall-still-info-bg",W:[{F:"span",N:"ytp-videowall-still-info-content",X:c,W:[{F:"span",N:"ytp-videowall-still-info-title",qa:"{{title}}"},{F:"span",
N:"ytp-videowall-still-info-author",qa:"{{author_and_views}}"},{F:"span",N:"ytp-videowall-still-info-live",qa:"En directo"},{F:"span",N:"ytp-videowall-still-info-duration",qa:"{{duration}}"}]}]}]},{F:"span",Ga:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],W:[{F:"span",N:"ytp-videowall-still-listlabel-icon"},"Lista de reproducci\u00f3n",{F:"span",N:"ytp-videowall-still-listlabel-length",W:[" (",{F:"span",qa:"{{playlist_length}}"},")"]}]},{F:"span",Ga:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],W:[{F:"span",N:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{F:"span",N:"ytp-videowall-still-listlabel-length",qa:" (50+)"}]}]});this.suggestion=null;this.u=d;this.api=a;this.j=new g.ZD(this);g.M(this,this.j);this.Ra("click",this.onClick);this.Ra("keypress",this.onKeyPress);this.j.T(a,"videodatachange",this.onVideoDataChange);a.Di(this.element,this);this.onVideoDataChange()},u6=function(a){p6.call(this,a,"videowall-endscreen");
var b=this;this.G=a;this.B=0;this.stills=[];this.C=this.videoData=null;this.D=this.J=!1;this.S=null;this.u=new g.ZD(this);g.M(this,this.u);this.Z=a.K("web_rounded_thumbnails");this.I=new g.Yn(function(){g.go(b.element,"ytp-show-tiles")},0);
g.M(this,this.I);var c=new g.W({F:"button",Ga:["ytp-button","ytp-endscreen-previous"],X:{"aria-label":"Anterior"},W:[g.dL()]});g.M(this,c);c.Ca(this.element);c.Ra("click",this.IU,this);this.table=new g.WK({F:"div",N:"ytp-endscreen-content"});g.M(this,this.table);this.table.Ca(this.element);c=new g.W({F:"button",Ga:["ytp-button","ytp-endscreen-next"],X:{"aria-label":"Siguiente"},W:[g.eL()]});g.M(this,c);c.Ca(this.element);c.Ra("click",this.HU,this);a.getVideoData().Me?this.j=new n6(a,!0):this.j=new q6(a);
g.M(this,this.j);g.CN(this.player,this.j.element,4);a.vb(this.element,this,158789);this.hide()},v6=function(a){return g.DN(a.player)&&a.Xx()&&!a.C},w6=function(a){var b=a.bf();
b!==a.J&&(a.J=b,a.player.ma("autonavvisibility"))},x6=function(a,b){g.W.call(this,{F:"button",
Ga:["ytp-watch-on-youtube-button","ytp-button"],X:{title:"{{message}}"},qa:"{{content}}"});this.G=a;this.buttonType=this.buttonType=b;switch(this.buttonType){case 1:a="Ver otra vez en YouTube";b=156915;break;case 2:a="Seguir reproduciendo en YouTube";b=156942;break;default:a="Seguir reproduciendo en YouTube",b=156942}this.update({message:a,content:a});this.G.vb(this.element,this,b);this.Ra("click",this.onClick)},y6=function(a){p6.call(this,a,"watch-again-on-youtube-endscreen");
this.watchButton=new x6(a,1);g.M(this,this.watchButton);this.watchButton.Ca(this.element);a.vb(this.element,this,156914);this.hide()},R4a=function(a){g.dO.call(this,a);
var b=this;this.endScreen=null;this.j=this.u=this.B=!1;this.listeners=new g.ZD(this);g.M(this,this.listeners);this.env=a.V();var c;(null==(c=g.sN(a))?0:c.lw())?this.endScreen=new y6(a):O4a(a)?(this.B=!0,P4a(this),this.j?this.endScreen=new r6(a):this.endScreen=new u6(this.player)):this.env.Ue?this.endScreen=new N4a(this.player):this.endScreen=new p6(this.player);g.M(this,this.endScreen);g.CN(this.player,this.endScreen.element,4);Q4a(this);this.listeners.T(a,"videodatachange",this.onVideoDataChange,
this);this.listeners.T(a,g.uA("endscreen"),function(d){b.onCueRangeEnter(d)});
this.listeners.T(a,g.vA("endscreen"),function(d){b.onCueRangeExit(d)})},P4a=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.Kk&&a.u===b.Me)return!1;a.j=b.Kk;a.u=b.Me;return!0},O4a=function(a){a=a.V();
return!a.B&&a.Lc&&!a.Ue},Q4a=function(a){a.player.Ff("endscreen");
var b=a.player.getVideoData();b=new g.sA(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.sA(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.qe([b,c])};
g.SO.prototype.xA=g.ba(30,function(a){this.UJ!==a&&(this.UJ=a,this.Dn())});
g.vN.prototype.Np=g.ba(4,function(){return this.app.Np()});
g.NX.prototype.Np=g.ba(3,function(){return this.getVideoData().HT});g.v(m6,g.W);m6.prototype.select=function(){(this.G.Ll(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Dy||void 0)||this.G.K("web_player_endscreen_double_log_fix_killswitch"))&&this.G.wb(this.element)};
m6.prototype.onClick=function(a){g.DO(a,this.G,this.j,this.suggestion.sessionData||void 0)&&this.select()};
m6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.Hx(a)||(this.select(),g.Gx(a))}};g.v(n6,g.W);g.k=n6.prototype;g.k.fB=function(a){this.suggestion!==a&&(this.suggestion=a,l6(this.j,a),this.playButton.Oa("url",this.suggestion.Nm()),o6(this))};
g.k.sj=function(){return 0<this.u};
g.k.Yw=function(){this.sj()||(this.u=Date.now(),H4a(this),G4a(this.G,J4a(this)),g.ko(this.G.getRootNode(),"countdown-running",this.sj()))};
g.k.ut=function(){this.Yo();H4a(this);var a=this.j.Da("ytp-autonav-endscreen-upnext-header");a&&g.sh(a,"Siguiente")};
g.k.Yo=function(){this.sj()&&(this.C.stop(),this.u=0)};
g.k.select=function(a){this.G.nextVideo(!1,void 0===a?!1:a);this.Yo()};
g.k.dM=function(a){g.DO(a,this.G)&&(a.currentTarget===this.playButton.element?this.G.wb(this.playButton.element):a.currentTarget===this.j.Da("ytp-autonav-endscreen-link-container")&&(a=this.j.Da("ytp-autonav-endscreen-link-container"),this.G.Xa(a,!0),this.G.wb(a)),this.select())};
g.k.CU=function(){this.G.wb(this.cancelButton.element);g.xN(this.G,!0);this.D&&this.G.Pa("innertubeCommand",this.D)};
g.k.onVideoDataChange=function(a,b){var c;this.D=null==(c=b.B6)?void 0:c.command};
g.k.K0=function(a){if(K4a(this)){var b=this.G.getVideoData().watchToWatchTransitionRenderer,c=null==b?void 0:b.fromColorPaletteDark;b=null==b?void 0:b.toColorPaletteDark;if(c&&b){var d=this.element;d.style.setProperty("--w2w-start-background-color",g.iM(c.surgeColor));d.style.setProperty("--w2w-start-primary-text-color",g.iM(c.primaryTitleColor));d.style.setProperty("--w2w-start-secondary-text-color",g.iM(c.secondaryTitleColor));d.style.setProperty("--w2w-end-background-color",g.iM(b.surgeColor));
d.style.setProperty("--w2w-end-primary-text-color",g.iM(b.primaryTitleColor));d.style.setProperty("--w2w-end-secondary-text-color",g.iM(b.secondaryTitleColor));d.style.setProperty("--w2w-animation-duration",a+"ms")}g.ko(this.element,"ytp-w2w-animate",!0)}};
g.k.BU=function(a){this.G.K("web_autonav_color_transition")&&2!==a&&g.ko(this.element,"ytp-w2w-animate",!1)};
g.k.cM=function(){var a=this.G.bf();this.I&&this.rb!==a&&g.ZK(this,a);o6(this);this.G.Xa(this.container.element,a);this.G.Xa(this.cancelButton.element,a);this.G.Xa(this.j.Da("ytp-autonav-endscreen-link-container"),a);this.G.Xa(this.playButton.element,a)};
g.k.Ig=function(a){return 400>a.width||459>a.height};g.v(p6,g.W);g.k=p6.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.Xx=function(){return!1};
g.k.bf=function(){return!1};
g.k.WP=function(){return!1};g.v(q6,g.W);g.k=q6.prototype;g.k.UB=function(){this.notification&&(this.C.stop(),this.yc(this.B),this.B=null,this.notification.close(),this.notification=null)};
g.k.fB=function(a){this.suggestion=a;l6(this,a,"hqdefault.jpg")};
g.k.eM=function(){g.ZK(this,this.api.bf());this.api.Xa(this.element,this.api.bf());this.api.Xa(this.Da("ytp-upnext-autoplay-icon"),this.api.bf());this.cancelButton&&this.api.Xa(this.cancelButton.element,this.api.bf())};
g.k.Q1=function(){window.focus();this.UB()};
g.k.Yw=function(a){var b=this;this.sj()||(g.Wx("a11y-announce","Siguiente "+this.suggestion.title),this.u=(0,g.T)(),this.j=new g.Yn(function(){M4a(b,a)},25),M4a(this,a),G4a(this.api,L4a(this,a)));
g.io(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.W.prototype.hide.call(this)};
g.k.sj=function(){return!!this.j};
g.k.ut=function(){this.Yo();this.u=(0,g.T)();M4a(this);g.go(this.element,"ytp-upnext-autoplay-paused")};
g.k.Yo=function(){this.sj()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(this.api.V().K("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.UB(),this.notification=new Notification("Siguiente",{body:this.suggestion.title,icon:this.suggestion.Nf()}),this.B=this.T(this.notification,"click",this.Q1),this.C.start())}this.Yo();this.api.nextVideo(!1,a)};
g.k.EU=function(a){!g.rh(this.cancelButton.element,g.Cx(a))&&g.DO(a,this.api)&&(this.api.bf()&&this.api.wb(this.Da("ytp-upnext-autoplay-icon")),this.select())};
g.k.DU=function(){this.api.bf()&&this.cancelButton&&this.api.wb(this.cancelButton.element);g.xN(this.api,!0)};
g.k.H1=function(a){this.api.getPresentingPlayerType();this.show();this.Yw(a)};
g.k.I1=function(){this.api.getPresentingPlayerType();this.Yo();this.hide()};
g.k.ra=function(){this.Yo();this.UB();g.W.prototype.ra.call(this)};g.v(r6,p6);g.k=r6.prototype;g.k.create=function(){p6.prototype.create.call(this);this.C.T(this.player,"appresize",this.Bx);this.C.T(this.player,"onVideoAreaChange",this.Bx);this.C.T(this.player,"videodatachange",this.onVideoDataChange);this.C.T(this.player,"autonavchange",this.fM);this.C.T(this.player,"autonavcancel",this.FU);this.onVideoDataChange()};
g.k.show=function(){p6.prototype.show.call(this);(this.I||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.xN(this.player,!1);g.DN(this.player)&&this.Xx()&&!this.B?(s6(this),2===this.videoData.autonavState?this.player.V().K("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.j.select(!0):this.j.Yw():3===this.videoData.autonavState&&this.j.ut()):(g.xN(this.player,!0),s6(this));this.Bx()};
g.k.hide=function(){p6.prototype.hide.call(this);this.j.ut();s6(this)};
g.k.Bx=function(){var a=this.player.dk(!0,this.player.isFullscreen());s6(this);o6(this.u);g.ko(this.element,"ytp-autonav-cancelled-small-mode",this.Ig(a));g.ko(this.element,"ytp-autonav-cancelled-tiny-mode",this.eD(a));g.ko(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.xl(this.overlay.element,{width:a.width+"px"});if(!this.D){a=g.r(this.videos.entries());for(var b=a.next();!b.done;b=a.next()){var c=g.r(b.value);b=c.next().value;c=c.next().value;g.ko(c.element,
"ytp-suggestion-card-with-margin",1===b%2)}}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length){var b=g.BI(this.videoData);b&&(this.j.fB(b),this.j!==this.u&&this.u.fB(b));for(b=0;b<S4a.length;++b){var c=S4a[b];if(a&&a[c]){this.videos[b]=new m6(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,l6(d,c));g.M(this,this.videos[b]);this.videos[b].Ca(this.J.element)}}}this.Bx()}};
g.k.fM=function(a){1===a?(this.I=!1,this.B=this.videoData.clientPlaybackNonce,this.j.Yo(),this.rb&&this.Bx()):(this.I=!0,this.bf()&&(2===a?this.j.Yw():3===a&&this.j.ut()))};
g.k.FU=function(a){a?this.fM(1):(this.B=null,this.I=!1)};
g.k.Xx=function(){return 1!==this.videoData.autonavState};
g.k.Ig=function(a){return(910>a.width||459>a.height)&&!this.eD(a)&&!(400>=a.width||360>=a.height)};
g.k.eD=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.bf=function(){return this.rb&&g.DN(this.player)&&this.Xx()&&!this.B};
var S4a=[1,3,2,4];g.v(N4a,p6);N4a.prototype.Ja=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.Jk;var b=this.subscribeButton;a.subscribed?b.u():b.B()};g.v(t6,g.W);t6.prototype.select=function(){(this.api.Ll(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Dy||void 0)||this.api.K("web_player_endscreen_double_log_fix_killswitch"))&&this.api.wb(this.element)};
t6.prototype.onClick=function(a){g.DO(a,this.api,this.u,this.suggestion.sessionData||void 0)&&this.select()};
t6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.Hx(a)||(this.select(),g.Gx(a))}};
t6.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.V();this.u=a.C?!1:b.u};g.v(u6,p6);g.k=u6.prototype;g.k.create=function(){p6.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.Jn();this.u.T(this.player,"appresize",this.Jn);this.u.T(this.player,"onVideoAreaChange",this.Jn);this.u.T(this.player,"videodatachange",this.onVideoDataChange);this.u.T(this.player,"autonavchange",this.sF);this.u.T(this.player,"autonavcancel",this.GU);a=this.videoData.autonavState;a!==this.S&&this.sF(a);this.u.T(this.element,"transitionend",this.q3)};
g.k.destroy=function(){g.bz(this.u);g.bf(this.stills);this.stills=[];p6.prototype.destroy.call(this);g.io(this.element,"ytp-show-tiles");this.I.stop();this.S=this.videoData.autonavState};
g.k.Xx=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){var a=this.rb;p6.prototype.show.call(this);g.io(this.element,"ytp-show-tiles");this.player.V().isMobile?g.$n(this.I):this.I.start();(this.D||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.xN(this.player,!1);v6(this)?(w6(this),2===this.videoData.autonavState?this.player.V().K("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.j.select(!0):this.j.Yw():3===this.videoData.autonavState&&this.j.ut()):(g.xN(this.player,!0),w6(this));a!==this.rb&&this.player.Xa(this.element,
!0)};
g.k.hide=function(){var a=this.rb;p6.prototype.hide.call(this);this.j.ut();w6(this);a!==this.rb&&this.player.Xa(this.element,!1)};
g.k.q3=function(a){g.Cx(a)===this.element&&this.Jn()};
g.k.Jn=function(){if(this.videoData&&this.videoData.suggestions&&this.videoData.suggestions.length){g.go(this.element,"ytp-endscreen-paginate");var a=this.G.dk(!0,this.G.isFullscreen()),b=g.sN(this.G);b&&(b=b.Vf()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),h=Math.max(a.height/54,2),l=this.videoData.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<h);){var p=b/2,q=e/2,u=b<=f-2&&n>=q*m,w=e<=h-2&&n>=p*m;if((p+
1)/q*d/c>c/(p/(q+1)*d)&&w)n-=p*m,e+=2;else if(u)n-=q*m,b+=2;else if(w)n-=p*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m=Math.floor(Math.min(a.width,m*c));n=Math.floor(Math.min(a.height,n*c));a=this.table.element;g.Hl(a,m,n);g.xl(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});this.j.fB(g.BI(this.videoData));this.j instanceof n6&&o6(this.j);g.ko(this.element,"ytp-endscreen-takeover",v6(this));w6(this);m+=4;n+=4;for(f=c=0;f<
b;f++)for(h=0;h<e;h++)if(p=c,u=0,d&&f>=b-2&&h>=e-2?u=1:0===h%2&&0===f%2&&(2>h&&2>f?0===h&&0===f&&(u=2):u=2),p=g.Cg(p+this.B,l),0!==u){q=this.stills[c];q||(q=new t6(this.player),this.stills[c]=q,a.appendChild(q.element));w=Math.floor(n*h/e);var y=Math.floor(m*f/b),A=Math.floor(n*(h+u)/e)-w-4,B=Math.floor(m*(f+u)/b)-y-4;g.Dl(q.element,y,w);g.Hl(q.element,B,A);g.xl(q.element,"transitionDelay",(h+f)/20+"s");g.ko(q.element,"ytp-videowall-still-mini",1===u);g.ko(q.element,"ytp-videowall-still-large",2<
u);this.Z&&(u=Math.max(B,A),g.ko(q.element,"ytp-videowall-still-round-large",256<=u),g.ko(q.element,"ytp-videowall-still-round-medium",96<u&&256>u),g.ko(q.element,"ytp-videowall-still-round-small",96>=u));p=this.videoData.suggestions[p];q.suggestion!==p&&(q.suggestion=p,u=q.api.V(),w=g.fo(q.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",l6(q,p,w),g.NF(u)&&(w=p.Nm(),y={},u.Aa&&g.dN(y,u.loaderUrl),w=g.vi(w,g.cN(y,"emb_rel_end")),q.Oa("url",w)),(p=(p=p.sessionData)&&p.itct)&&q.api.Ck(q.element,
p));c++}g.ko(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.ph(e.element),g.af(e);this.stills.length=c}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.B=0,this.videoData=a,this.Jn())};
g.k.HU=function(){this.B+=this.stills.length;this.Jn()};
g.k.IU=function(){this.B-=this.stills.length;this.Jn()};
g.k.WP=function(){return this.j.sj()};
g.k.sF=function(a){1===a?(this.D=!1,this.C=this.videoData.clientPlaybackNonce,this.j.Yo(),this.rb&&this.Jn()):(this.D=!0,this.rb&&v6(this)&&(2===a?this.j.Yw():3===a&&this.j.ut()))};
g.k.GU=function(a){if(a){for(a=0;a<this.stills.length;a++)this.G.Xa(this.stills[a].element,!0);this.sF(1)}else this.C=null,this.D=!1;this.Jn()};
g.k.bf=function(){return this.rb&&v6(this)};g.v(x6,g.W);x6.prototype.onClick=function(a){g.EO(this.getVideoUrl(),this.G,a);this.G.wb(this.element)};
x6.prototype.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.G.getVideoUrl(a,!1,!1,!0);var b=this.G.V();if(g.NF(b)||g.YF(b)){var c={};b.Aa&&g.NF(b)&&g.dN(c,b.loaderUrl);a:{switch(this.buttonType){case 2:b="emb_ytp_continue_watching";break a}b="emb_ytp_watch_again"}g.cN(c,b);a=g.vi(a,c)}return a};
x6.prototype.show=function(){g.W.prototype.show.call(this);this.G.Xa(this.element,!0)};
x6.prototype.hide=function(){g.W.prototype.hide.call(this);this.G.Xa(this.element,!1)};g.v(y6,p6);y6.prototype.show=function(){if(3!==this.player.getPlayerState()){p6.prototype.show.call(this);var a;null==(a=g.sN(this.player))||a.xA(!0);this.player.Xa(this.element,!0)}};
y6.prototype.hide=function(){p6.prototype.hide.call(this);var a;null==(a=g.sN(this.player))||a.xA(!1);this.player.Xa(this.element,!1)};g.v(R4a,g.dO);g.k=R4a.prototype;g.k.Ot=function(){var a;if(null==(a=g.sN(this.player))?0:a.lw())return!0;a=this.player.getVideoData();var b=!!(a&&a.suggestions&&a.suggestions.length);b=!O4a(this.player)||b;var c=a.Vg||g.YF(a.Sa),d=this.player.Ky();a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.k.bf=function(){return this.endScreen.bf()};
g.k.b_=function(){return this.bf()?this.endScreen.WP():!1};
g.k.ra=function(){this.player.Ff("endscreen");g.dO.prototype.ra.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.transitionEndpointAtEndOfStream;if(b&&b.videoId){var c=this.player.ub().ke.get("heartbeat");a&&a.suggestions&&a.suggestions.length&&b.videoId===a.suggestions[0].videoId&&!a.AN?a=!1:(this.player.Ll(b.videoId,void 0,void 0,!0,!0,b),c&&c.kD("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0)}else a=!1;a||(g.dO.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.dO.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.Ot()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){Q4a(this);this.B&&P4a(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new r6(this.player):this.endScreen=new u6(this.player),g.M(this,this.endScreen),g.CN(this.player,this.endScreen.element,4))};g.cO("endscreen",R4a);})(_yt_player);
